### ISSUE TITLE
bug(ci): affected typecheck loses plugin-anthropic declarations and segfaults

### ISSUE THREAD

**Issue by lalalune** [elizaOS/eliza#15753]
Parent: #13631

## Problem

The Develop PR `typecheck` job failed after PR #15750 with:

```text
@elizaos/plugin-capacitor-bridge:typecheck: packages/agent/src/runtime/optional-plugin-imports.generated.ts(35,47): error TS7016: Could not find a declaration file for module '@elizaos/plugin-anthropic'.
... plugins/plugin-anthropic/dist/node/index.node.js implicitly has an 'any' type.
There are types at plugins/plugin-anthropic/index.ts, but this result could not be resolved when respecting package.json exports.
```

The Turbo process then segfaulted (exit 139). PR #15750 merged before the late failure completed, so MVP closeout can presently merge with a red typecheck.

Source run: https://github.com/elizaOS/eliza/actions/runs/29046628158/job/86216794255

## Acceptance criteria

- [ ] Reproduce the affected typecheck from a clean install/build ordering.
- [ ] `@elizaos/plugin-anthropic` exports resolvable declarations for every exported runtime entry.
- [ ] `optional-plugin-imports.generated.ts` typechecks when consumed by plugin-capacitor-bridge before and after plugin build.
- [ ] Seed a regression that fails when an optional plugin package export resolves JS without a declaration target.
- [ ] The affected typecheck lane passes without segfault.
- [ ] Attach the failing and passing logs and identify whether the segfault is causal or secondary.

No UI evidence applies.

**Comment by lalalune** [comment]
CLAIMING: reproduce and repair plugin-anthropic declaration resolution in the affected typecheck graph, add an export/declaration regression, and verify the exact plugin-capacitor-bridge consumer path.

**Comment by lalalune** [comment]
PR #15754 opened. Causal result: plugin-anthropic build emits all package.json declaration targets; the failing bridge task had no graph edge to that build. The fix declares Anthropic as a bridge devDependency, and Turbo's resolved graph now shows @elizaos/plugin-anthropic#build as a direct prerequisite of @elizaos/plugin-capacitor-bridge#typecheck. Graph audit passes with no phantom edges/cycles. Clean CI typecheck remains the acceptance gate.

**Comment by lalalune** [comment]
CLEAN CI PROOF: PR #15754 Develop PR typecheck now passes with the derived Anthropic build prerequisite. Build, lint-and-types, unit, integration, security, coverage, and evidence checks also pass. This confirms the prior TS7016 was caused by missing declaration build order. The earlier exit-139 segfault did not recur once the type error was removed, so it was secondary to the failing Turbo run. Waiting for the remaining e2e/aesthetic jobs before merge.

**Comment by lalalune** [comment]
Review against the exact current-base filtered task disproved the Anthropic-only dependency fix: after Anthropic built, bridge typecheck failed on five more undeclared agent-source dependencies. PR #15754 now fixes the boundary itself by typechecking through the existing mobile shims; the exact Turbo task passes 6/6 with no provider dependency or lockfile change.
