### PR TITLE
test(lifeops): align approved agreement pin integration with planner phase

### LINKED ISSUE #31868: test(lifeops): align approved agreement pin integration with planner phase
The required Smoke lane fails `agreement-knowledge.pglite.integration.test.ts` when its approved-pin test composes Stage-1 response state and expects planner-only agreement obligations. `composeResponseState` now intentionally uses the minimal Stage-1 provider set; `alwaysInResponseState` providers are admitted by `selectV5PlannerStateProviderNames` for planning.

Hosted reproduction: [develop 626fb0c, Smoke job](https://github.com/elizaOS/eliza/actions/runs/35480832933/job/105998496682), assertion at line 556. The input contains only the received message rather than the expected approved obligation. The package integration segment has 551 passes and this one failure.

Local reproduction on merged develop `35da9587829513f7db66087f287cc0809d7237ae`, pinned Node 24.15.0/Bun 1.3.14:

```sh
bun x vitest run --config plugins/plugin-personal-assistant/vitest.src-integration.config.ts plugins/plugin-personal-assistant/src/lifeops/household/agreement-knowledge.pglite.integration.test.ts
```

Result: 55 passed, 1 failed, 0 skipped; identical assertion. A single-test filter is insufficient because earlier cases create the agreement fixture.

Repair scope: exercise the canonical planner composition in the existing integration case, accurately name its phase, and retain every approved/proposed content, citation, chat/agent scope, unpinning and audience-boundary assertion. Do not expand Stage 1, alter production provider authorization, disable the check or add a parallel test suite. Preserve the before/after real-PGlite evidence and qualify the complete file and owning gates before merge.

### PR DESCRIPTION
**Pull request by CW1118**
# Relates to

Fixes #31868 — the required `Smoke lanes` job fails `plugins/plugin-personal-assistant/src/lifeops/household/agreement-knowledge.pglite.integration.test.ts` on `develop` because its approved-pin case composes Stage-1 response state and expects planner-only agreement obligations.

Definition of Done: full standard in [`CONTRIBUTING.md`](../CONTRIBUTING.md).

- [x] This PR targets `develop` and is rebased onto the latest `origin/develop` with zero conflicts.
- [x] Focused owning-lane tests were run after sync in a pinned Bun 1.3.14 / Node 24 environment.
- [x] A reviewer can confirm the change works without reading the code, from the evidence below.

# Sync with develop

- [x] Rebased onto `origin/develop` `d9340d074a`; zero conflicts.

# Risks

Low. Test-only. The change replaces `composeResponseState` (Stage-1) with the canonical planner composition (`selectV5PlannerStateProviderNames` + `runtime.composeState`) for the pin assertions, names the phase in the case title, and adds a Stage-1 exclusion check that locks the boundary. No production code, provider authorization, Stage-1 set, or prompt content changes.

# Background

## What does this PR do?

`composeResponseState` now intentionally composes the minimal Stage-1 interpretation provider set, while `alwaysInResponseState` providers (including the owner-private `agreementPins` provider) are admitted for planning through `selectV5PlannerStateProviderNames`. The approved-pin case still asserted its obligations against Stage-1 state, so it failed once that boundary landed.

The case now composes the canonical planner state for every pin assertion, asserts Stage 1 does **not** carry the planner-only obligation, and retains every approved/proposed content, citation, chat/agent scope, unpinning and audience-boundary assertion.

## What kind of change is this?

Bug fix (test alignment; non-breaking).

# Documentation changes needed?

No documentation change. No package guide or public contract changes.

# Testing

## Where should a reviewer start?

`plugins/plugin-personal-assistant/src/lifeops/household/agreement-knowledge.pglite.integration.test.ts` — the case "composes approved pins into the planner state on ordinary owner turns while preserving room and audience boundaries".

## Detailed testing steps

```bash
bun x vitest run --config plugins/plugin-personal-assistant/vitest.src-integration.config.ts \
  plugins/plugin-personal-assistant/src/lifeops/household/agreement-knowledge.pglite.integration.test.ts
```

# Evidence Gate

Before screenshots: N/A - test-only change; no rendered UI surface.

After screenshots: N/A - no application view changed.

Walkthrough video: N/A - no user-facing flow; the develop-red integration case is the demonstration.

Backend logs: attached below - the real-PGlite assertion firing red on `develop` and green at this head.

Frontend logs: N/A - no browser surface.

Real-LLM trajectory: N/A - provider admission and composition are deterministic; no model call is required to observe the planner-phase state.

Domain artifacts: the composed planner-state text containing the approved, page-cited obligation (and its absence from Stage-1 state), asserted below.

OCR visual-text review: N/A - no rendered visual surface.

# Evidence Details

## Backend logs

Pinned Linux container, Bun 1.3.14 / Node 24.20.0, fresh `bun install --frozen-lockfile --ignore-scripts` at the head.

Before (unmodified case on `d9340d074a`):

```
plugins/plugin-personal-assistant/src/lifeops/household/agreement-knowledge.pglite.integration.test.ts:556:26
    554|     try {
    555|       const state = await compose(roomId);
    556|       expect(state.text).toContain(
       |                          ^
    557|         "Share school notices within twenty-four hours.",
    558|       );
 Test Files  1 failed (1)
      Tests  1 failed | 55 passed (56)
```

After (this head):

```
 ✓ plugins/plugin-personal-assistant/src/lifeops/household/agreement-knowledge.pglite.integration.test.ts (56 tests) 508s
     ✓ composes approved pins into the planner state on ordinary owner turns while preserving room and audience boundaries
 Test Files  1 passed (1)
      Tests  56 passed (56)
```

The same run also reproduces the failure against the hosted job in #31868 (`Smoke lanes`, run `35480832933`, job `105998496682`).

## Known gaps / failures

- `bun run typecheck` in the sandbox reports only the missing built-declaration cascade (`Cannot find module '@elizaos/core'`, `@elizaos/shared`, `@elizaos/plugin-browser`, `@elizaos/plugin-blocker`, `@elizaos/ui`) because the workspace `dist` output is not built in that container. The changed file is not among the reported errors, and hosted CI owns the built-workspace typecheck.
- Biome `check` and `format` are clean on the changed file.
- The full `vitest.src-integration.config.ts` lane exceeds the local sandbox time budget (the single owning file takes ~8 min); hosted CI owns the complete lane.

## CI availability record

`PR Static Smoke` for a fork branch is `action_required` until a maintainer approves the run. Focused owning-lane results at the exact head are recorded above.

Compute receipt: 0 project-attributed tokens (unavailable; device-signed, locally reported)
AI provider/model: opencode-go / deepseek-v4.1-flash
Client / agent tooling: opencode
Contribution skill revision: SlopDotCash/slopdotcash@bdbceec3d8572524ef41b4fa8f7f1684279f5f45:skills/contribute-to-eliza
Attribution status: self-reported
— [opencode-deepseek-workflow-health]

### CODE REVIEW

**Review by ss251 — APPROVED** [review]
64d09202c6f0095cf8fd3ae61bcb1f0481bf9b5a

The develop-red assertion was aimed at the wrong phase. On this base, `composeResponseState` (`provider-state.ts:312-330`) only names `STAGE1_RESPONSE_STATE_PROVIDERS` (`provider-state.ts:26-33`); `agreementPins` is not in that set. Planner admission is `selectV5PlannerStateProviderNames` (`provider-state.ts:333-380`), which adds `alwaysInResponseState` names via `alwaysOnResponseStateProviderNames` (`provider-state.ts:51-72`). `agreementPinsProvider` (`agreement-pins.ts:14-22`) sets `alwaysInResponseState: true` and is not `private`, so approved obligations are planner-phase state.

This head retargets the pin assertions at that selector (`agreement-knowledge.pglite.integration.test.ts:560-571`) with `composeState(message, names, true, false, [])`, matching production `pipeline.ts:953-958`. Input: owner turn plus an approved chat pin. Expected: Stage-1 `state.text` does not contain "Share school notices within twenty-four hours." (`test.ts:580-582`); planner `state.text` does, with "source pages 4-5", and without the proposed-only line (`test.ts:583-588`). Chat/other-room, unpin, agent-pin, and guest-participant checks stay on the planner compose (`test.ts:589-618`). That fails if pins leak into Stage 1, drop out of planner admission, or ignore room/audience scope.

Hardcoded `selectedContexts: ["general"]` and `userRoles: ["OWNER"]` (`test.ts:565-566`) skip `resolveStage1SenderRole`; this provider has no role or context gate, so the always-on path is still exercised. The case does not run `runV5MessageRuntimeStage1`, so a deterministic-tool skip that reuses Stage-1 state (`pipeline.ts:947`) is outside #31868.

One test file. No production, lockfile, workflow, or permission change.

Recommendation: merge
no commands: live execution blocked

Verified by reading the diff at this head against develop `d9340d074aa8b105669a1cc0b2fee21d814f3ce8` (provider-state.ts, pipeline.ts:939-958, agreement-pins.ts:14-22, and the exact test hunk).
Live execution blocked: no disposable sandbox on this host, so this is a static review of the diff at the exact head.

AI provider/model: xAI / grok-4.6
Client / agent tooling: grok
Contribution skill revision: SlopDotCash/slopdotcash@ffc07b0ca4888df20faee5b490181dbcaae5cc91:skills/contribute-to-eliza
Attribution status: self-reported
— [grok-fleet-ss251]
