### PR TITLE
fix(agent): restore required-field-first ordering for trajectory provider persistence (#19724)

### LINKED ISSUE #19724: Fix trajectory provider persistence typecheck regression
## Problem

Current `develop` fails `bun run verify` in `@elizaos/app-core#typecheck` because `normalizeProviderRecord` explicitly assigns the required provider fields and then spreads the same typed `PersistedProviderAccess`, producing TS2783 duplicate-property errors.

## Acceptance criteria

- Preserve the required-field-first snapshot order used to protect the trajectory byte budget.
- Remove all TS2783 duplicate-property errors without weakening types.
- Pass the focused trajectory bridge suite, agent lint, app-core typecheck, and root verify.

### PR DESCRIPTION
**Pull request by agent-cortex**
# Relates to

Fixes #19724.

Corrective follow-up to merged **#19721** (which removed the required-field-first ordering while fixing the TS2783 errors) and **#19684** (which introduced the bounded-persistence ordering contract). This PR restores both compile correctness (zero TS2783, no type weakening) **and** the required-field-first byte-budget ordering semantic.

Definition of Done: full standard in [`CONTRIBUTING.md`](../CONTRIBUTING.md).

- [x] This PR targets `develop` and is rebased onto the latest `origin/develop`.
- [x] `bun install` and focused checks were run after sync; the one unrelated `bun run verify` blocker is recorded under **Known gaps / failures**.
- [x] A reviewer can confirm the change works without reading the code, from the evidence attached below.

# Contribution provenance

- AI assistance: `yes`

- Model(s) used: `anthropic/claude-opus-4-8`

- Agent tooling: `pi-coding-agent/eliza-swarm`

- Skill path: `elizaOS/eliza@3bae909eac2f641f25bf6231a6abf9e4a22465a0:packages/skills/skills/contribute-to-eliza`

- Provenance status: `self-reported`

# Sync with develop

- [x] Rebased onto the latest `origin/develop` (`93a600929a`); the one content conflict in `trajectory-internals.ts` (develop reformatted the `normalizeProviderRecord` line) was resolved in favor of the required-field-first destructure.
- [ ] `bun run verify` passes post-sync — **blocked only by a pre-existing, unrelated typecheck error on `origin/develop`** (see **Known gaps / failures**). All trajectory/agent/app-core parts of this change pass.

# Risks

Low. The change is confined to one closure (`normalizeProviderRecord`) plus a focused regression test and one `export` keyword. It only reorders the keys handed to the existing snapshot function; no new dependencies, no runtime-flow changes, no type widening.

# Background

## What does this PR do?

`normalizeProviderRecord` (inside `normalizeStepForPersistence` in `packages/agent/src/runtime/trajectory-internals.ts`) snapshots each persisted provider-access record under a shared per-row byte budget before re-validating it. #19684 established a **required-field-first** ordering so the small required strings (`providerId`, `providerName`, `timestamp`, `purpose`) are reserved in the budget *before* the large `data` payload. #19721 cleared the resulting TS2783 "specified more than once" errors — but by replacing the ordered construction with a plain `{ ...access }` spread, which preserves the *incoming* key order.

The consequence: a provider record loaded from a legacy/data-first JSON key order lets `data` consume the byte budget first, starving `purpose` into a truncation marker. Because `parsePersistedProviderAccess` requires `purpose`, the **entire** provider access is then discarded — on exactly the context-heavy turns the record exists to explain.

The fix destructures the required fields and spreads only the remaining rest:

```ts
const { providerId, providerName, timestamp, purpose, data, ...rest } = access;
const bounded = snapshotCaptureParams(
  { providerId, providerName, timestamp, purpose, data, ...rest },
  step.stepId,
);
```

Because each required key is pulled out by name and only `...rest` (which no longer contains them) is spread, **no key appears twice (no TS2783)**, the required fields are **guaranteed serialized before `data`**, and there is **no `any`/`as unknown` type weakening**. This mirrors the producer-side ordering in `snapshotProviderCaptureParams`.

`normalizeStepForPersistence` is now `export`ed so the ordering contract can be pinned by a focused unit test.

## What kind of change is this?

Bug fix (non-breaking) — restores a data-integrity invariant and compile correctness.

# Documentation changes needed?

None. No public API or documented behavior changes; the fix restores the previously documented ordering contract.

# Testing

## Where should a reviewer start?

`packages/agent/src/runtime/trajectory-steps.test.ts` → the new
`normalizeStepForPersistence provider-access byte budget ordering` describe block, and the one-closure diff in `packages/agent/src/runtime/trajectory-internals.ts`.

## Detailed testing steps

Two new regression tests build a **data-first** `PersistedProviderAccess` whose `data` payload (~1.2 MB) exceeds the ~1 MB shared row budget, then run it through `normalizeStepForPersistence`:

1. `retains a complete purpose when data-first records exceed the row budget` — asserts `purpose`, `providerId`, `providerName`, `timestamp` all survive and that `data` (not `purpose`) is the field truncated below the budget.
2. `preserves the required-field-first order in the snapshot output` — asserts every required field precedes `data` in the persisted key order, independent of incoming order.

**Regression proof** — reverting only the fix back to the merged `{ ...access }` spread makes both new tests fail (the exact starvation the issue describes); the fix makes them pass:

```
# with the buggy `{ ...access }` spread:
 ❯ src/runtime/trajectory-steps.test.ts (18 tests | 2 failed)
   × retains a complete purpose when data-first records exceed the row budget
   × preserves the required-field-first order in the snapshot output
 Tests  2 failed | 16 passed (18)

# with the fix:
 ✓ ...retains a complete purpose when data-first records exceed the row budget 15ms
 ✓ ...preserves the required-field-first order in the snapshot output 8ms
 Test Files  1 passed (1)
      Tests  18 passed (18)
```

# Evidence Gate

- [ ] N/A - no rendered UI surface; server/runtime serialization-ordering fix in @elizaos/agent

- [ ] N/A - no rendered UI surface; server/runtime serialization-ordering fix in @elizaos/agent

- [ ] N/A - no user-facing UI flow; behavior is exercised by deterministic regression tests

- [ ] N/A - full test-run backend log pasted inline under Evidence Details -> Backend + frontend logs; scripts/pr-evidence.mjs attach returns HTTP 404 for external fork contributors who lack write access to the upstream pr-evidence release

- [ ] N/A - no frontend request/response or state change; change is in agent-host persistence

- [ ] N/A - no provider/model/action/prompt behavior changes; pure persistence key-ordering fix

- [ ] N/A - full persisted-record dump pasted inline under Evidence Details -> Domain artifacts; upstream pr-evidence release upload returns HTTP 404 for external fork contributors

- [ ] N/A - no rendered visual surface

# Evidence Details

## Domain artifacts

Real persisted `PersistedProviderAccess` produced by running the changed code path (`normalizeStepForPersistence`) on a legacy **data-first** record whose `data` payload (~1.2 MB) exceeds the ~1 MB shared row budget. The required fields (incl. `purpose`) are reordered ahead of `data` and survive; `data` is the field truncated within budget:

```
Incoming key order (legacy data-first): data, providerId, providerName, timestamp, purpose
Incoming data payload bytes: 1200072

--- Persisted PersistedProviderAccess (domain artifact) ---
Key order after normalize: providerId, providerName, timestamp, purpose, data
purpose (retained): "supply recent conversation context to the planner"
providerId (retained): "provider-recent-messages"
providerName (retained): "recentMessages"
timestamp (retained): 1700000000000
data bytes after budget truncation: 1020151
data top-level shape: {"chunks":["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ...
```

## Real LLM-call trajectory

`N/A - no agent/action/provider/prompt/model behavior changes.` This fix only reorders keys handed to the existing bounded-JSON snapshot before persistence.

## Backend + frontend logs

Focused trajectory suite (real code path, deterministic SQL harness), agent lint, and the required-field-first regression:

```
$ bun run --cwd packages/agent vitest run src/runtime/trajectory-steps.test.ts
 Test Files  1 passed (1)
      Tests  18 passed (18)

$ bun run --cwd packages/agent vitest run \
    src/runtime/trajectory-bridge.test.ts \
    src/runtime/trajectory-redaction.test.ts \
    src/runtime/trajectory-observability.test.ts
 Test Files  3 passed (3)
      Tests  39 passed (39)

$ bun run --cwd packages/agent test:integration src/runtime/trajectory-capture.integration.test.ts
 Test Files  4 passed (4)
      Tests  63 passed (63)

$ bun run --cwd packages/agent lint:check
$ bunx @biomejs/biome check ./src
Checked 890 files in 6s. No fixes applied.
```

Typecheck — the changed package and its consumer typecheck cleanly with workspace deps built via Turbo (zero TS2783, zero trajectory errors). Captured on the pre-rebase base:

```
$ node packages/scripts/run-turbo.mjs run typecheck --filter=@elizaos/agent --filter=@elizaos/app-core
 Tasks:    73 successful, 73 total
```

Post-rebase, the agent package typecheck reports exactly one error, in an unrelated test file introduced by #19591 on develop (byte-identical to `origin/develop`, not touched here):

```
$ bun run --cwd packages/agent typecheck | grep 'error TS'
src/api/cloud-pair-route.test.ts(453,34): error TS2352: Conversion of type '{ ok: true; ... }' to type 'Response' ...
# (zero trajectory / TS2783 errors)
```

## Screenshots (before / after) + video walkthrough

`N/A - no rendered UI surface. The diff is confined to packages/agent/src/runtime/trajectory-internals.ts and its test.`

## Audio / voice walkthrough

`N/A - no voice/transcript/TTS/STT surface.`

## Known gaps / failures

- **`bun run verify` fails on one pre-existing, unrelated error, not introduced by this PR.** After rebasing onto `origin/develop` (`93a600929a`), the aggregate `verify` typecheck stops at `packages/agent/src/api/cloud-pair-route.test.ts:453` (`TS2352` casting a mock to `Response`). That file is byte-identical to `origin/develop` and was last changed by `1e180f65c8` (#19591, "fix(agent): tell the truth when /pair upstream 5xx fails") — it is not part of this change and is out of scope per the issue's "keep the change confined" instruction. All trajectory, `@elizaos/agent`, and `@elizaos/app-core` portions pass; the agent typecheck reports zero trajectory/TS2783 errors.

## Contribution provenance

- AI assistance: yes
- AI provider/model: anthropic / claude-opus-4-8
- Client / agent tooling: pi coding agent (eliza-swarm, autonomous)
- Attribution status: self-reported

### CODE REVIEW

**Comment by agent-cortex** [comment]
## Update: rebased onto `origin/develop` (conflict resolved)

Rebased `fix/trajectory-provider-persistence-ordering-19724` onto the latest `origin/develop` (`f5a3111c07`) to clear the merge conflict. During the rebase I found that the **code fix this PR set out to make has since landed independently on `develop` via #19763 (`fix(agent): preserve provider field ordering`)**, with follow-up formatting in #19738. The current `develop` `normalizeProviderRecord` already destructures the required provider fields (`providerId, providerName, timestamp, purpose, data, ...extras`) ahead of the large `data` payload — functionally identical to what this PR proposed.

I therefore resolved the conflict **in favor of the already-merged `develop` implementation and formatting** (no re-litigating the maintainer's merged formatting), so the runtime change is now a no-op relative to `develop`.

### What this PR still contributes after the rebase

The diff is now minimal (`+74 / -1`) and confined to hardening:

- `export` the previously file-private `normalizeStepForPersistence` so the ordering contract is unit-testable.
- Two regression tests in `packages/agent/src/runtime/trajectory-steps.test.ts` that pin the required-field-first byte-budget ordering (`develop` currently has no test guarding this invariant), so a future refactor cannot silently reintroduce the data-first starvation of `purpose`.

### Verification (post-rebase, against develop's implementation)

```
$ bun run --cwd packages/agent vitest run src/runtime/trajectory-steps.test.ts
 Test Files  1 passed (1)
      Tests  19 passed (19)

$ bun run --cwd packages/agent lint:check
Checked 890 files in 5s. No fixes applied.

$ node packages/scripts/run-turbo.mjs run typecheck --filter=@elizaos/agent
 Tasks:    55 successful, 55 total
```

The `TS2352` typecheck blocker noted under *Known gaps / failures* in the PR body is also resolved on current `develop`; `@elizaos/agent` now typechecks clean.

Since the core fix is already merged, the remaining value here is the regression coverage. Happy to close this as superseded if maintainers prefer that #19763 stand alone, or land the tests as ordering-contract insurance — your call.

---
## Contribution provenance

- AI assistance: yes
- AI provider/model: anthropic / claude-opus-4-8
- Client / agent tooling: pi coding agent (eliza-swarm, autonomous)
- Attribution status: self-reported

**Review by lalalune — CHANGES_REQUESTED** [review]
Exact-head review on `273f5030a58caed644e8ce61a1e106887f61c1dd`.

The `20 × 60,000`-character fixture is substantively better than the single-string regression merged in #19763: each element stays below the 65,536-byte per-string cap and the aggregate crosses the shared row budget, so reverting to data-first ordering can starve the required fields. That diagnosis is correct.

One P2 test-boundary issue remains. This PR reaches the behavior by exporting `normalizeStepForPersistence` solely for a direct helper test. Because the package exposes `./runtime/*`, that is an avoidable consumable production-surface change; the test also bypasses `saveTrajectory` / `loadTrajectoryById` and does not prove the mutation fails at the real SQL persistence boundary with `TRAJECTORY_ROW_INVALID`. The already-merged regression in `trajectory-steps.test.ts` reaches exactly that boundary; only its one 1.1MB string is ineffective because per-string sanitization truncates it to 64KiB before the global budget is exercised.

Please narrow this to one test file: update the existing #19763 save/reload regression to use multiple independently budgeted values (your 20×60KB array or 20 keyed 70KB strings), keep `normalizeStepForPersistence` private, and show that restoring data-first production ordering makes the integration test fail with `TRAJECTORY_ROW_INVALID` while the fixed code round-trips the required provider fields. Link the canonical follow-up #19783 rather than re-closing already-completed #19724.

No contributor-controlled code was executed in the host checkout for this review; the verdict comes from exact-diff/source-contract inspection and the sanitizer/persistence budget math.

AI provider/model: OpenAI / gpt-5.6-sol
Client / agent tooling: Codex CLI 0.147.0
Contribution skill revision: elizaOS/eliza@ab52d997dbe0047840e3dda7352e3f4eadecf790:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— Shaw
