### PR TITLE
fix(ci): keep bridge typecheck inside its mobile boundary

### LINKED ISSUE #15753: bug(ci): affected typecheck loses plugin-anthropic declarations and segfaults
Parent: #13631

## Problem

The Develop PR `typecheck` job failed after PR #15750 with:

```text
@elizaos/plugin-capacitor-bridge:typecheck: packages/agent/src/runtime/optional-plugin-imports.generated.ts(35,47): error TS7016: Could not find a declaration file for module '@elizaos/plugin-anthropic'.
... plugins/plugin-anthropic/dist/node/index.node.js implicitly has an 'any' type.
There are types at plugins/plugin-anthropic/index.ts, but this result could not be resolved when respecting package.json exports.
```

The Turbo process then segfaulted (exit 139). PR #15750 merged before the late failure completed, so MVP closeout can presently merge with a red typecheck.

Source run: https://github.com/elizaOS/eliza/actions/runs/29046628158/job/86216794255

## Acceptance criteria

- [ ] Reproduce the affected typecheck from a clean install/build ordering.
- [ ] `@elizaos/plugin-anthropic` exports resolvable declarations for every exported runtime entry.
- [ ] `optional-plugin-imports.generated.ts` typechecks when consumed by plugin-capacitor-bridge before and after plugin build.
- [ ] Seed a regression that fails when an optional plugin package export resolves JS without a declaration target.
- [ ] The affected typecheck lane passes without segfault.
- [ ] Attach the failing and passing logs and identify whether the segfault is causal or secondary.

No UI evidence applies.

### PR DESCRIPTION
**Pull request by lalalune**
Closes #15753. Parent #13631.

## Outcome

Keeps the Capacitor bridge's leaf typecheck inside the same explicit mobile boundary used by its declaration build.

The initial Anthropic-only proposal was insufficient: after Anthropic built successfully, the exact filtered bridge task failed next on `@elizaos/skills`, plugin-vision, background-runner, native-filesystem, and cloud-sdk. The root cause was not one missing provider edge. `tsconfig.json` aliases the full agent source tree, whose optional-plugin graph is not—and cannot safely become—the dependency graph of a leaf package that the agent itself depends on.

The corrected change:

- runs package-local typecheck with `tsconfig.build.json`;
- uses the existing type-only agent root/API/runtime shims instead of pulling all agent source into the task;
- updates stale root and in-process dispatch shim signatures so they are actually checked rather than hidden by declaration build `--noCheck`;
- adds a contract test pinning the typecheck config and the three agent shim paths;
- adds no optional provider dependency and no lockfile churn.

## Verification

- exact current-base filtered bridge typecheck: 6/6 Turbo tasks passed;
- focused boundary contract: 1/1 passed, 3 assertions;
- Biome passed on the four changed files;
- `git diff --check` passed;
- review also proved the replaced workaround failed the same exact command after Anthropic succeeded.

## Evidence

- [ ] N/A - CI/type-boundary repair with no rendered UI.

- [ ] N/A - CI/type-boundary repair with no rendered UI.

- [ ] N/A - no interactive user-facing flow changed.

- [x] [Original failing CI log](https://github.com/elizaOS/eliza/actions/runs/29046628158/job/86216794255) and [current-base review/fix transcript](https://github.com/elizaOS/eliza/releases/download/pr-evidence/15754-bridge-typecheck-review.log)

- [ ] N/A - no frontend/browser runtime changed.

- [ ] N/A - no model request, prompt, provider behavior, or agent trajectory changed.

- [x] [Issue #15753 with causal failure and acceptance criteria](https://github.com/elizaOS/eliza/issues/15753)

- [ ] N/A - no screenshots apply.

### CODE REVIEW

**Comment by lalalune** [comment]
CI follow-up: the coverage lane ran the file-contract test successfully but emitted no LCOV because that test only read shim files as text. I added a runtime-boundary regression that imports every changed shim guard and proves each throws `Type shim only` if runtime resolution ever reaches it. Local Bun coverage now records 3/3 lines for `agent-api.ts` and 15/15 for `agent-root.ts` (100% on both), while retaining the package/config contract assertions. Pushed as ac022488e9; fresh CI is running.

**Comment by lalalune** [comment]
CI status audit: the failing Test Integrity lane is unrelated to this dependency declaration. Per-plugin e2e coverage reports three now-unused baseline entries for plugin-birdclaw (missing-action-e2e, missing-deterministic-e2e, missing-view-e2e) in packages/scripts/lint-lane-coverage.allowlist.json. All 142 plugins otherwise report 0 blocking issues. This is develop-side ratchet drift and should be removed by the #13620 coverage owner rather than folded into this scoped PR.

**Comment by lalalune** [comment]
## Verify pass ([shaw-agent])

Reset a throwaway worktree to the PR head (`cdfe6c22dd`), fresh `bun install --frozen-lockfile`, and ran the real gate.

**Decisive gate — GREEN, independently and in CI**
- Local: `bun run --cwd plugins/plugin-capacitor-bridge typecheck` (`tsgo --noEmit -p tsconfig.build.json`) → **exit 0, no output, no segfault**.
- CI: the `typecheck` job on `cdfe6c22dd` (`Develop PR` run 29052933539) → **completed/success**.
- New contract test `capacitor-bridge-typecheck-boundary.test.ts` → **2 pass / 10 asserts**, 100% coverage on both shim files (non-vacuous).

**Root cause confirmed independently.** `plugin-anthropic`'s `exports` already declare `types` targets for node/browser/bun — so acceptance #2 ("resolvable declarations") is a package-ordering race, not a missing exports entry. The bridge failed because its base `tsconfig.json` aliases `@elizaos/agent/*` → `packages/agent/src/*`, pulling `optional-plugin-imports.generated.ts`, whose `import("@elizaos/plugin-anthropic")` (line 35) resolves through node_modules → dist with no build-ordering guarantee (bridge does not depend on anthropic). Agent's own typecheck is safe because anthropic/vision/background-runner are its `dependencies` (built via `^build`). The reframe (isolate the leaf via shims) is the correct fix.

**Coverage is airtight for the bridge:** the only agent specifiers in bridge src are exactly `@elizaos/agent`, `@elizaos/agent/api`, `@elizaos/agent/runtime` — all three shimmed in `tsconfig.build.json`; no subpath falls through to node_modules. Shims fail-fast (`throw new Error("Type shim only")`) — no fabricated defaults/empties, no empty catch, no console. Typecheck now actually checks the shim signatures (previously hidden by declaration-build `--noCheck`). No collision with other open PRs (only #15754 touches these files).

**Non-blocking notes (follow-up, not merge blockers):**
1. Acceptance #4 ("seed a regression that fails when an optional plugin export resolves JS without a declaration target") is satisfied only for the chosen remedy — the contract test pins *this* leaf's boundary. Other leaf packages that alias `@elizaos/agent` source and don't depend on a given optional plugin remain latently exposed to the same race if a future `--affected` set includes them unbuilt. Empirically only the bridge failed, so this is residual-risk hardening, not a blocker.
2. Acceptance #6 asks to state whether the segfault is causal or secondary; the PR body doesn't call it out explicitly. It's secondary (Turbo crashes *after* the TS7016/TS2307 surfaces) — worth one line in the body.

Verdict: **MERGE-READY** once CI is fully green.
