### PR TITLE
chore(tests): remove duplicate cloud suite wrappers

### LINKED ISSUE #31704: test(cloud): remove redundant composite suite wrappers
Six cloud-shared composite lane files import24already-discovered test files and add only `expect(typeof test).toBe("function")`. Their comments claim independent isolation or complete lifecycle coverage, but they do not connect the imported suites into one lifecycle. The normal package runner recursively discovers every original test and owns process isolation.

A real Bun1.3.14 `--isolate` run confirms duplicate registration: shared billing original alone runs7tests/51assertions; original plus eliza-sandbox-16639-lane2-billing wrapper runs15tests/103assertions, with the same7behavioral cases twice plus1runner self-check. Tracked-reference search found no direct wrapper callers in scripts, manifests or workflows.

Scope: retire eliza-sandbox-16639-lanes2/3/4/5,provisioning-jobs-16639-lane and docker-sandbox-provider-lane (100lines total), retaining all24original suites and existing Windows quarantine/process sharding. Verify each original executes, compare retained test names, and investigate isolation requirements before removal. Do not replace real errors with skipped tests or claim independent unit suites constitute a complete lifecycle.

Acceptance: no unique behavior lost,no dangling consumers,no weaker runner isolation; package checks and root verification pass. The originals are currently being exercised in separate Bun processes; results are not yet complete.

### PR DESCRIPTION
**Pull request by lalalune**
Remove six cloud test wrappers that import suites already discovered by the package runner and assert that Bun's test function exists. Importing suites does not create a complete lifecycle test or enforce process isolation; the package runner already owns discovery and process batching.

This deletes 100 lines with no additions. All 24 original suites remain unchanged, retaining 392 cases for billing, bridge failures and streaming, container quota, provisioning, and Docker lifecycle boundaries. Closes #31704.

Validation:
- A real isolated Bun run of the billing original executes seven cases; wrapper plus original executes 15: seven repeated cases and one runner self-check.
- All 24 originals pass through the actual package run-bun-tests.mjs batching path: 392 passed, zero failed across five children, with existing heavy-suite classification unchanged.
- Caller search found no external script, manifest or workflow targeting these wrappers.
- Frozen install passed in this installed checkout with unchanged dependency manifests and lockfile.
- Root verification passes: 373 tasks plus all subsequent repository audits, including test-lane membership and focused/skip checks. Fresh fetch/rebase leaves the validated source unchanged.

Three standalone suites initially failed to import generated output during a concurrent root build. They passed unchanged after that build; the complete selected batch then passed. This does not claim full-package, live-provider or installed-host certification. Billing replay CI on develop currently needs launcher dependency repair #31703; that separate repair has passed actual local and hosted payment replay.

N/A - test wrappers only; no rendered change.

N/A - test wrappers only; no rendered change.

N/A - no product behavior changes.

N/A - no backend implementation changes.

N/A - no frontend implementation changes.

N/A - no model or prompt changes.

N/A - no rendered change.

```text
Real Bun isolated billing original: 7 pass, 51 expect() calls.
Billing original plus wrapper: 15 pass, 103 expect() calls.
Selected original family through package run-bun-tests.mjs: 24 files, 5 child batches, 392 pass, 0 fail.
Root verify: 373 successful tasks, 373 total, 6m26.027s.
[audit-test-lane-membership] every test-bearing package is accounted for
[anti-larp] clean — no focused tests, no untracked skips.
```

### CODE REVIEW

**Review by ss251 — APPROVED** [review]
Reviewed head 15404a1f8ad48694b2c6f61a15e486c8f9939236.

The risky part of these six deletions is whether the composed suites are still discovered without the wrappers. I matched every deleted wrapper's imports against Bun's default test glob: all 24 imported files are sibling `*.test.ts` or `__tests__/*.test.ts`, all survive, all match `**/*.test.ts` — so no suite is dropped and no import points at a deleted file.

Tradeoff: lane2/lane5 comments say the separate entries existed to isolate PGlite/fetch/stub state; after deletion those suites compose in one Bun process, so the isolation rationale is gone — expect possible order-dependent flakes, not lost coverage.

Verified by reading the full diff and matching each deleted import against Bun's default discovery; suite not run.

Recommendation: merge  
no commands: live execution blocked

Compute receipt: 0 project-attributed tokens (unavailable; device-signed, locally reported)
AI provider/model: deepseek / deepseek-v4-flash
Client / agent tooling: review-lane-free
Contribution skill revision: SlopDotCash/slopdotcash@74f222c2271634a7f36b4470eab7380f978092ba:skills/contribute-to-eliza
Attribution status: self-reported
— [review]

**Review by attentionhead — APPROVED** [review]
Approve.

Verified at head `15404a1f8ad48694b2c6f61a15e486c8f9939236`, merge-base `b928f9c32a76fa2f0807210b26f7c0cfa65f9e53` (derived locally with `git merge-base origin/develop <head>`, not taken from the API).

**Scope.** `git diff --name-status $MB..$H` lists exactly the six deleted wrappers and nothing else (+0/-100). `packages/cloud/shared/scripts/run-bun-tests.mjs`, `packages/core/` and `plugins/plugin-web-search/` are byte-identical across the range.

On a deletion PR the load-bearing question is not "is the deleted file referenced" but "is what it wrapped still reachable without it". Checked in that order:

1. **No external references.** None of the six wrapper basenames appears anywhere in the tree at the merge-base (each checked individually).
2. **The wrappers carry no assertions of their own.** Each is a list of `import "./<suite>.test.ts"` lines plus a trivial `expect(typeof test).toBe("function")` self-check. Across the six they name 24 distinct originals.
3. **All 24 originals are present at head**, including `__tests__/eliza-sandbox-coding-container-quota.test.ts`, which only `eliza-sandbox-16639-lane5-quota.test.ts` referenced.
4. **Discovery does not depend on the wrappers.** `discoverTestFiles()` walks the package recursively, skipping only `.git/.tmp/.turbo/build/coverage/dist/node_modules` — `__tests__/` is not skipped — and `TEST_FILE_PATTERN` matches every original. So each wrapped suite was already scheduled in its own right; the wrappers added duplicate execution, not coverage.
5. **`node packages/scripts/audit-test-lane-membership.mjs` at head: exit 0**, every test-bearing package accounted for.

**On the process-isolation rationale in the deleted docblocks** (fetch/WebSocketPair stubs bleeding, PGlite/module-state collisions): the 13 docker suites named by `docker-sandbox-provider-lane.test.ts` run green individually at head, totalling 201 passing assertions, and yield exactly the same 201 passes when composed into a single runner batch. No bleed reproduced in either arrangement.

**Baselines actually run** (`packages/cloud/shared`, `node scripts/run-bun-tests.mjs`, driven through the runner's own `ELIZA_BUN_TEST_FILES_JSON` manifest seam so real sharding and PGlite batching apply):

- head, the 24 originals: sharded to 5 children, batch 1 = **201 pass / 3 fail (3 errors)**, run aborts at batch 1.
- merge-base, the same 24 plus the 6 wrappers: sharded to 7 children, **403 pass / 2 fail (2 errors)**, also aborts at batch 1.

**Scope limit — pre-existing environment failure, not a defect of this PR.** Those failures are not assertion failures. They are `Cannot find module '@elizaos/core/edge' from plugins/plugin-web-search/src/edge.ts`. `packages/core` declares `"./edge"` mapping to `./dist/edge/index.edge.js`, and that artifact is absent in this checkout, while `@elizaos/core` and `hono` both resolve as controls. Per-file at head: the 13 docker suites are green (201 pass); the 7 `provisioning-jobs-*` suites and `eliza-sandbox-coding-container-quota` each fail on that missing build artifact. The same suites fail identically at the merge-base (spot control: `provisioning-jobs-execute-dispatch`, `provisioning-jobs-lanes` and the quota suite all fail there too, while `docker-sandbox-replacement-cleanup` is 72/72 green on both sides). I therefore could not obtain a fully green package run at either revision and do not claim one; the comparison above is like-for-like across the same broken artifact.

No mutation testing: a pure-deletion change has no implementation zone to mutate. The claim under test was reachability, which is settled by items 1-5 above.

**Comment by lalalune** [comment]
Reviewed exact head `15404a1f8ad48694b2c6f61a15e486c8f9939236`. This deletes six wrappers and 100 lines, with no additions. Verified all 24 imported original suites remain byte-identical to the base. Each wrapper only imports already-discovered tests and asserts Bun's test function exists; none establishes process isolation. The unchanged package runner owns discovery and heavy-suite batching.

Inspected the actual package-runner batch log: 392 retained cases pass across five children. Root verification completed 373 tasks and subsequent audits. The direct comparison shows the seven-case billing original becomes 15 cases with its wrapper (seven duplicated cases plus a runner self-check). No production code or test implementation is removed.

Hosted billing replay failed before cloud health on this old head; repair #31703 is now merged and passed hosted replay. At review time source/static and Windows checks are still running, PostgreSQL passes. These pending/failed checks are not represented as passing. Proceeding with the reviewed deletion-only diff and completed local validation; the resulting develop workflow remains required follow-up evidence.
