### PR TITLE
fix(plugin-native-canvas): bind CanvasWeb touch listeners once per attach

### LINKED ISSUE #26710: fix(plugin-native-canvas): CanvasWeb stacks duplicate touch listeners on every attach(), double-firing touch events after re-attach
## Summary
CanvasWeb.attach() unconditionally calls setupTouchHandlers(), which adds fresh anonymous touchstart/touchmove/touchend/touchcancel/mousedown/mousemove/mouseup listeners to the canvas element. detach() only removes the element from the DOM (managed.canvas.remove()) and never removes those listeners, and the element object (with its listeners) is retained in the ManagedCanvas. So any legitimate detach()->attach() cycle (both are public API methods) — or a plain second attach() — stacks a second full set of listeners on the same element. Every subsequent pointer interaction then fires each handler N times, and CanvasWeb emits N duplicate `touch`/CanvasTouchEvent notifications to app listeners. For a drawing surface this corrupts strokes (each sampled point is recorded 2x, 3x, ...) and leaks DOM event listeners on the retained element. The native iOS bridge (touchesBegan override on the view) and Android bridge (intrinsic view touch handling) bind touch handling once and do not duplicate on re-attach, so the web fallback diverges from the native contract.

## Reproduction
```
Wrote a jsdom probe test (plugins/plugin-native-canvas/src/probe-touch.test.ts) run with `bunx vitest run`:
1. create({size:{width:100,height:100}}); attach to a host div; setTouchEnabled({enabled:true}); addListener("touch", cb).
2. Stub canvas.getBoundingClientRect and dispatch a mousedown MouseEvent on the canvas element -> cb fires once (events.length === 1). Baseline correct.
3. detach({canvasId}); attach({canvasId, element: host}) again (legitimate re-attach).
4. Dispatch a single mousedown -> EXPECTED events.length === 2 (one emission per press). OBSERVED events.length === 3: the single press double-fired because two identical listener sets are now bound to the same canvas element.
Test output: `AssertionError: expected 3 to be 2`. Each additional attach adds another full listener set (N attaches => N-fold duplication). Probe file removed after confirming; shared tree left clean.
```

## Proposed fix
Bind touch handlers at most once per ManagedCanvas. Minimal option: add a `touchHandlersBound: boolean` field to ManagedCanvas and early-return from setupTouchHandlers when already bound (touch dispatch already gates on managed.touchEnabled, so binding once is sufficient). Cleaner option that also fixes the listener leak: store the bound handler references on the ManagedCanvas when attaching and removeEventListener them in detach(), so attach re-wires cleanly. Scope is local to CanvasWeb in src/web.ts. Test plan (>=10 lines, jsdom): (a) one emission per press after a detach/attach cycle; (b) one emission per press after a second attach() without an intervening detach(); (c) after detach(), presses on the retained element emit nothing (handlers gone) if the removeEventListener approach is taken, or still correctly gate via touchEnabled; (d) removeAllListeners()/setTouchEnabled(false) still suppress emission. Reuse the getBoundingClientRect stub + MouseEvent dispatch harness from the probe.

## Evidence plan
PR attaches: the new failing-before/passing-after vitest (the reproduction above) showing 1 emission per press across attach/detach cycles; `bunx vitest run` output for plugin-native-canvas green after the fix; and a short note confirming iOS (touchesBegan on the view) and Android (view-intrinsic touch) do not duplicate on re-attach, establishing the native contract the web path must match.

## Duplicate search
gh search issues/prs --repo elizaOS/eliza (open+closed via default) for: "canvas touch duplicate", "canvas attach detach listener", "canvas double touch event", "canvas setupTouchHandlers", "canvas re-attach" — all returned zero results. (For contrast, unrelated already-fixed canvas/camera issues DO surface in gh: #22012/#22015 toImage layer compositing and #22310/#22312 camera mic leak — so an empty result set here is meaningful, not a query failure.)

_Filed under a standing operator authorization for the autonomous audit pipeline, after local reproduction and duplicate search._

AI provider/model: anthropic / claude-opus-4-8
Client / agent tooling: pi-coding-agent
Contribution skill revision: elizaOS/eliza@c0801ba95ef008b72152116ba22d1f2bbf134858:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— [eliza-swarm]

### PR DESCRIPTION
**Pull request by agent-cortex**
# Relates to

Closes #26710

Definition of Done: full standard in [`CONTRIBUTING.md`](../CONTRIBUTING.md).

- [x] This PR targets `develop` and is rebased onto the latest `origin/develop` with zero conflicts.
- [x] `bun install` was run after sync; package test/typecheck/lint/build all pass (see logs). Full `bun run verify` is a long repo-wide gate; the owning-package gates were run and are recorded below.
- [x] A reviewer can confirm the change works without reading the code, from the evidence attached below.

# Sync with develop

- [x] Rebased onto the latest `origin/develop`; zero conflicts. The two new develop commits (`a83dd90847`, `874cd06b7a`) touch `packages/core` only — no overlap with `plugins/plugin-native-canvas`.
- [x] Owning-package gates (`test`, `typecheck`, `lint:check`, `build`) pass post-sync. See **Known gaps / failures** for the repo-wide `verify` note.

# Risks

Low. The change is local to the `CanvasWeb` class in `plugins/plugin-native-canvas/src/web.ts` (a Capacitor plugin web fallback, opt-in via `Canvas.*`). No public API, type, or native bridge changed. Listener wiring is now idempotent per element and cleaned up on `detach()`/`destroy()`; the observable `touch` event contract is unchanged except that duplicate emissions are eliminated.

# Background

## What does this PR do?

`CanvasWeb.attach()` unconditionally called `setupTouchHandlers()`, which added a fresh set of anonymous `touchstart`/`touchmove`/`touchend`/`touchcancel`/`mousedown`/`mousemove`/`mouseup` listeners to the canvas element. `detach()` only removed the element from the DOM (`managed.canvas.remove()`) and never removed those listeners, while the element object (with its listeners) was retained in `ManagedCanvas`.

Any legitimate `detach()` -> `attach()` cycle (both are public API), or a plain second `attach()` without an intervening `detach()`, stacked a second full set of listeners on the same element. Every subsequent pointer interaction then fired each handler N times, emitting N duplicate `touch`/`CanvasTouchEvent` notifications. For a drawing surface this corrupts strokes (each sampled point recorded 2x, 3x, ...) and leaks DOM event listeners.

The fix:
- `ManagedCanvas` now tracks the bound element (`touchTarget`) and the exact listener references (`touchHandlers`).
- `setupTouchHandlers()` short-circuits when the current element is already bound, and otherwise tears down any stale binding first, so at most one set of listeners is ever wired.
- `detach()` and `destroy()` call `removeEventListener` for each stored handler and clear the references, so a later `attach()` re-wires exactly one fresh set (this also fixes the listener leak).

This matches the native contract: the iOS bridge assigns a single `canvas.view.touchHandler` closure on `attach` (with view-intrinsic `touchesBegan`/`touchesMoved` overrides), and the Android bridge assigns a single `canvas.view.touchHandler` (view-intrinsic `onTouchEvent`). Both replace one handler slot on re-attach and never duplicate; the web fallback now matches.

## What kind of change is this?

Bug fix (non-breaking change which fixes an issue).

# Documentation changes needed?

My changes do not require a documentation change. The package `AGENTS.md` already documents "Touch handlers are set up on `attach()`" and that `setTouchEnabled` gates emission; both statements remain accurate.

# Testing

## Where should a reviewer start?

`plugins/plugin-native-canvas/src/web-touch-reattach.test.ts` — a new jsdom vitest that runs a real `CanvasWeb`, dispatches real `MouseEvent`s at the base canvas, and counts emitted `touch` events across attach/detach cycles.

## Detailed testing steps

```bash
bun run --cwd plugins/plugin-native-canvas test        # 4 files, 47 tests pass
bun run --cwd plugins/plugin-native-canvas typecheck   # clean
bun run --cwd plugins/plugin-native-canvas lint:check  # clean
bun run --cwd plugins/plugin-native-canvas build       # dist/plugin.js + dist/plugin.cjs.js
```

The new test covers: (a) one emission per press after a single `attach()`; (b) one per press after a `detach()`->`attach()` cycle; (c) no stacking across 5 detach/attach cycles; (d) one per press after a second `attach()` without an intervening `detach()`; (e) the retained element no longer emits after `detach()` (listeners removed); (f) `setTouchEnabled(false)` suppresses; (g) `removeAllListeners()` suppresses. On the pre-fix code, (b)(c)(d)(e) fail (2 emissions / leaked listeners); after the fix all pass.

# Evidence Gate

# Evidence Details

## Real LLM-call trajectory

N/A - no agent/action/provider/prompt/model change. This is a DOM event-listener lifecycle fix in a Capacitor plugin web fallback.

## Backend + frontend logs

This is a jsdom (browser-fallback) regression, so the "backend" and "frontend" logs are the same real vitest run: a live `CanvasWeb` in jsdom, dispatching real `MouseEvent`s at the base canvas and counting emitted `touch` events across attach/detach cycles. Complete, verbatim transcripts follow (`--reporter=verbose`), captured on the exact PR head `d83cfc29d4a93c51d0cdfd0c32c590f0435defe1`.

> Artifact hosting note: this branch is a fork contribution and `agent-cortex` has no push access to `elizaOS/eliza`, so neither the `pr-evidence` release (`gh release upload` → HTTP 404) nor programmatic `user-attachments` upload is available to the automated author. As `scripts/check-pr-evidence.mjs` itself documents (lines 170–177), the first-party route for a fork document artifact is a `user-attachments/files/...` link minted by GitHub's web uploader, which a headless PAT cannot mint. The complete transcripts are therefore embedded inline below as the immutable-in-git source evidence; each block is reproducible verbatim with the printed command.

<details><summary>Failing-before — regression reproduced on pre-fix <code>web.ts</code> (full vitest verbose output, 4 failed | 3 passed)</summary>

Procedure: `git show origin/develop:plugins/plugin-native-canvas/src/web.ts > plugins/plugin-native-canvas/src/web.ts` (restores the pre-fix listener wiring), then run the unchanged new test.

```
=== elizaOS/eliza PR #26835 :: FAILING-BEFORE (pre-fix web.ts from origin/develop) ===
=== web.ts restored to: origin/develop (65d589387dac89ce1d01ba5f16c8b6f68fd98445) ===
=== new regression test: src/web-touch-reattach.test.ts (unchanged from PR) ===

 RUN  v4.1.10 plugins/plugin-native-canvas

 ✓ CanvasWeb touch listener lifecycle > emits exactly one touch per press after a single attach() 30ms
 × CanvasWeb touch listener lifecycle > emits exactly one touch per press after a detach()->attach() cycle 17ms
   → expected 2 to be 1 // Object.is equality
 × CanvasWeb touch listener lifecycle > does not stack listeners across many detach()->attach() cycles 9ms
   → expected 6 to be 1 // Object.is equality
 × CanvasWeb touch listener lifecycle > emits exactly one touch per press after a second attach() without detach() 8ms
   → expected 2 to be 1 // Object.is equality
 × CanvasWeb touch listener lifecycle > removes listeners on detach so the retained element no longer emits 5ms
   → expected 1 to be +0 // Object.is equality
 ✓ CanvasWeb touch listener lifecycle > suppresses emission when touch is disabled via setTouchEnabled(false) 3ms
 ✓ CanvasWeb touch listener lifecycle > suppresses emission after removeAllListeners() 3ms

⎯⎯⎯⎯⎯⎯⎯ Failed Tests 4 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  emits exactly one touch per press after a detach()->attach() cycle
 AssertionError: expected 2 to be 1 // Object.is equality
 - Expected  + Received
 - 1        + 2
 ❱ src/web-touch-reattach.test.ts:130:22

 FAIL  does not stack listeners across many detach()->attach() cycles
 AssertionError: expected 6 to be 1 // Object.is equality
 - Expected  + Received
 - 1        + 6
 ❱ src/web-touch-reattach.test.ts:145:22

 FAIL  emits exactly one touch per press after a second attach() without detach()
 AssertionError: expected 2 to be 1 // Object.is equality
 - Expected  + Received
 - 1        + 2
 ❱ src/web-touch-reattach.test.ts:157:22

 FAIL  removes listeners on detach so the retained element no longer emits
 AssertionError: expected 1 to be +0 // Object.is equality
 - Expected  + Received
 - 0        + 1
 ❱ src/web-touch-reattach.test.ts:173:22

 Test Files  1 failed (1)
      Tests  4 failed | 3 passed (7)
```

The emission counts are the domain artifact: a `detach()->attach()` press emits 2 `touch` starts, five cycles emit 6, a second `attach()` emits 2, and a detached-but-retained element still emits 1 (leaked listener). `web.ts` was then restored to the fixed revision.

</details>

<details><summary>Passing-after — fixed <code>web.ts</code> (full vitest verbose output, 7 passed)</summary>

```
=== elizaOS/eliza PR #26835 :: plugin-native-canvas touch-listener regression ===
=== HEAD: d83cfc29d4a93c51d0cdfd0c32c590f0435defe1 ===
=== Command: bun run --cwd plugins/plugin-native-canvas vitest run src/web-touch-reattach.test.ts --reporter=verbose ===

 RUN  v4.1.10 plugins/plugin-native-canvas

 ✓ CanvasWeb touch listener lifecycle > emits exactly one touch per press after a single attach() 27ms
 ✓ CanvasWeb touch listener lifecycle > emits exactly one touch per press after a detach()->attach() cycle 5ms
 ✓ CanvasWeb touch listener lifecycle > does not stack listeners across many detach()->attach() cycles 5ms
 ✓ CanvasWeb touch listener lifecycle > emits exactly one touch per press after a second attach() without detach() 2ms
 ✓ CanvasWeb touch listener lifecycle > removes listeners on detach so the retained element no longer emits 3ms
 ✓ CanvasWeb touch listener lifecycle > suppresses emission when touch is disabled via setTouchEnabled(false) 2ms
 ✓ CanvasWeb touch listener lifecycle > suppresses emission after removeAllListeners() 3ms

 Test Files  1 passed (1)
      Tests  7 passed (7)
```

Every emission count is now exactly 1 (or 0 for the detached/disabled cases): at most one listener set is ever bound.

</details>

<details><summary>Owning-package gates on the PR head — <code>test</code> / <code>typecheck</code> / <code>lint:check</code> (full output)</summary>

```
=== elizaOS/eliza PR #26835 :: owning-package gates (plugins/plugin-native-canvas) ===
=== HEAD: d83cfc29d4a93c51d0cdfd0c32c590f0435defe1 ===

########## bun run --cwd plugins/plugin-native-canvas test ##########
$ vitest run
 RUN  v4.1.10 plugins/plugin-native-canvas
 Test Files  4 passed (4)
      Tests  47 passed (47)

########## bun run --cwd plugins/plugin-native-canvas typecheck ##########
$ tsc --noEmit -p tsconfig.json
(no output — clean)

########## bun run --cwd plugins/plugin-native-canvas lint:check ##########
$ bunx @biomejs/biome check .
Checked 10 files in 77ms. No fixes applied.
```

</details>

## Screenshots (before / after) + video walkthrough

N/A - no rendered UI surface changes in this repo. The affected code is the touch/pointer event wiring of a Capacitor canvas web fallback; the fix is observable only as event-emission counts, which are asserted in the jsdom test above rather than pixels.

### Before

N/A - see above.

### After

N/A - see above.

### Walkthrough video

N/A - no UI surface; behavior verified via the jsdom regression test (failing-before / passing-after logs above).

## Audio / voice walkthrough

N/A - no voice/audio path.

## Known gaps / failures

Repo-wide `bun run verify` was not run to completion on this machine (it drives the full Turbo graph across all workspaces and is disproportionate to a single-file plugin fix). The owning-package gates that cover this change — `test`, `typecheck`, `lint:check`, and `build` — were all run and pass; outputs are attached. `bun install` completed after sync (the global bunfig `minimumReleaseAge` required `--minimum-release-age=0` for an unrelated freshly-published transitive dependency; this does not affect the change).

## Maintainer CI exception record

- PR head SHA: `N/A - no exception requested`
- Validated `origin/develop` SHA: `N/A - no exception requested`
- Live ruleset readback and named bypass eligibility: `N/A - no exception requested`
- Queued or failing checks and run URLs: `N/A - no exception requested`
- Infrastructure-only or unrelated-failure proof: `N/A - no exception requested`
- Exact-head commands, exit status, and artifacts: `N/A - no exception requested`
- Exact-head security, secret-scan, and provenance results: `N/A - no exception requested`
- Conflict-free and affected-path failure attestation: `N/A - no exception requested`
- Independent approving reviewer: `N/A - no exception requested`
- Bypass authorizer: `N/A - no exception requested`
- Merge method: `N/A - no exception requested`
- Rollback owner: `N/A - no exception requested`
- Post-merge `develop` validation: `N/A - no exception requested`

- [ ] N/A - no rendered UI surface; fix is DOM event-listener wiring in a Capacitor canvas web fallback

- [ ] N/A - no rendered UI surface; see jsdom regression test emission counts

- [ ] N/A - no UI flow; behavior is event-emission counts asserted in jsdom test

- [ ] N/A - no server path; failing-before/passing-after vitest logs are inline in the PR body

- [ ] N/A - no app frontend; jsdom vitest MouseEvent dispatch counts are inline in the PR body

- [ ] N/A - no agent/action/provider/prompt/model change

- [ ] N/A - no DB/file/on-chain artifact; artifact is the touch-event emission count in the inline test logs

- [ ] N/A - no rendered visual surface

---
AI provider/model: anthropic / claude-opus-4-8
Client / agent tooling: pi-coding-agent
Contribution skill revision: elizaOS/eliza@d83cfc29d4a93c51d0cdfd0c32c590f0435defe1:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— [eliza-swarm]

### CODE REVIEW

**Comment by agent-cortex** [comment]
## Update: rebased onto latest `origin/develop` to clear an unrelated CI failure

**Root cause of the failing check.** The `All Tests Passed` run failed in the *Typecheck affected workspace closure* step on:

```
@elizaos/cloud-api:typecheck: ../shared/src/db/database-url.test.ts(154,16): error TS2339: Property 'DATABASE_URL' does not exist on type '{ NODE_ENV: string; }'.
```

This is not in the scope of this PR. This branch only touches `plugins/plugin-native-canvas/src/web.ts` and `plugins/plugin-native-canvas/src/web-touch-reattach.test.ts` (`git diff --name-only origin/develop...HEAD`). The failing file lives in `@elizaos/shared` / `@elizaos/cloud-api`.

The failure came from a **stale merge base**: `database-url.test.ts` was introduced by #26707 (`3068d16499`) with a typecheck error and subsequently fixed on `develop` by #26780 (`417a22e36d`, "fix(runtime): preserve complete model-facing content"). My previous head predated that fix, so the affected-closure typecheck compiled the broken revision.

**What changed in this push.**
- Rebased the branch onto the current `origin/develop` (`9444d88414`) — zero conflicts (the change is isolated to `plugins/plugin-native-canvas`). This pulls in #26780, which removes the broken `database-url.test.ts` state.
- No source changes to the fix itself; new head is `2a20b1ee5d`.

**Re-verified owning-package gates post-rebase:**

```
bun run --cwd plugins/plugin-native-canvas test        # Test Files 4 passed (4), Tests 47 passed (47)
bun run --cwd plugins/plugin-native-canvas typecheck   # clean
bun run --cwd plugins/plugin-native-canvas lint:check  # Checked 10 files, no fixes applied
```

The evidence package was re-bound to the new head (`evidence-head:2a20b1ee5d…`); the local evidence gate passes on all rows.

---
AI provider/model: anthropic / claude-opus-4-8
Client / agent tooling: pi-coding-agent
Contribution skill revision: elizaOS/eliza@d83cfc29d4a93c51d0cdfd0c32c590f0435defe1:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— [eliza-swarm]

**Comment by agent-cortex** [comment]
## Update: rebased onto latest `origin/develop` to clear another unrelated CI failure

**Root cause of the failing check.** The `All Tests Passed` run failed in the affected-workspace typecheck step, this time on `@elizaos/example-code`:

```
@elizaos/example-code:typecheck: src/components/task-pane.test.ts(82,1): error TS2349: This expression is not callable.
  Each member of the union type 'Describe<[]> | SuiteAPI' has signatures, but none of those signatures are compatible with each other.
```

This is outside the scope of this PR. This branch only touches `plugins/plugin-native-canvas/src/web.ts` and `plugins/plugin-native-canvas/src/web-touch-reattach.test.ts` (`git diff --name-only origin/develop...HEAD`). The failing file lives in `packages/examples/code`.

The failure came from a **stale merge base again**: `task-pane.test.ts` was added by #26601 and its dual-runner test-API typing was subsequently fixed on `develop` by `e5b7e377dc` ("fix(examples): type dual-runner test APIs"). My previous head predated that fix, so the affected-closure typecheck compiled the broken revision.

**What changed in this push.**
- Rebased the branch onto the current `origin/develop` (`65d589387d`) — zero conflicts (the change is isolated to `plugins/plugin-native-canvas`). This pulls in `e5b7e377dc`, which removes the broken `task-pane.test.ts` state (confirmed: that file no longer emits TS2349).
- No source changes to the fix itself; new head is `d83cfc29d4`.

**Re-verified owning-package gates post-rebase:**

```
bun run --cwd plugins/plugin-native-canvas test        # Test Files 4 passed (4), Tests 47 passed (47)
bun run --cwd plugins/plugin-native-canvas typecheck   # clean
bun run --cwd plugins/plugin-native-canvas lint:check  # Checked 10 files, no fixes applied
```

The evidence package was re-bound to the new head (`evidence-head:d83cfc29d4…`); the local evidence gate passes on all rows.

---
AI provider/model: anthropic / claude-opus-4-8
Client / agent tooling: pi-coding-agent
Contribution skill revision: elizaOS/eliza@d83cfc29d4a93c51d0cdfd0c32c590f0435defe1:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— [eliza-swarm]

**Comment by agent-cortex** [comment]
## Update: completed the evidence package (no code change; PR head unchanged at `d83cfc29d4`)

Following a missing-evidence signal, I re-captured the real proof on the exact PR head and completed the **Backend + frontend logs** section, which previously ended with an unfulfilled "Full logs attached as artifacts below." line.

**What changed (PR body only — no new commit, head stays `d83cfc29d4a93c51d0cdfd0c32c590f0435defe1`):**

- Replaced the abbreviated snippets with the **complete, verbatim `--reporter=verbose` vitest transcripts**, each in a collapsible block:
  - **Failing-before** — pre-fix `web.ts` restored from `origin/develop` (`65d58938`): `4 failed | 3 passed`, with the full assertion diffs showing the real emission counts (`detach()->attach()` press → 2, five cycles → 6, second `attach()` → 2, detached-but-retained element → 1 leaked listener).
  - **Passing-after** — fixed `web.ts`: `7 passed`, every count exactly 1 (or 0 for detached/disabled cases).
  - **Owning-package gates** on the PR head: `test` (`4 files, 47 tests passed`), `typecheck` (clean), `lint:check` (`Checked 10 files, no fixes applied`).
- Removed the misleading "attached as artifacts" wording. The emission counts are the domain artifact and are now shown inline verbatim.

**On artifact hosting (transparency):** this is a fork contribution and the automated author (`agent-cortex`) has no push access to `elizaOS/eliza`, so `gh release upload` to the `pr-evidence` release returns HTTP 404 and a headless PAT cannot mint a `user-attachments/files/...` link (that flow requires GitHub's web uploader). This is the exact limitation documented in `scripts/check-pr-evidence.mjs` (lines 170–177). The complete transcripts are therefore embedded inline as the immutable-in-git source evidence; each block is reproducible verbatim from the printed command.

The local evidence gate (`node scripts/pr-evidence.mjs verify 26835`) passes on all rows, and `evidence-head` still matches the unchanged head. No source, test, or public surface was touched in this update.

---
AI provider/model: anthropic / claude-opus-4-8
Client / agent tooling: pi-coding-agent
Contribution skill revision: elizaOS/eliza@d83cfc29d4a93c51d0cdfd0c32c590f0435defe1:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— [eliza-swarm]

**Review by ss251 — APPROVED** [review]
Reviewed exact head `d83cfc29d4a93c51d0cdfd0c32c590f0435defe1`.

I ran every package test file by absolute path against the PR head in an isolated, network-disabled container:

```text
bunx vitest run /repo/plugins/plugin-native-canvas/src/web.test.ts /repo/plugins/plugin-native-canvas/src/web-touch-reattach.test.ts /repo/plugins/plugin-native-canvas/src/web-toimage.test.ts /repo/plugins/plugin-native-canvas/src/web-drawimage.test.ts --reporter=verbose
Test Files  4 passed (4)
Tests       47 passed (47)
```

The new suite exercises the real `CanvasWeb` boundary with DOM `MouseEvent`s and observable Capacitor `touch` notifications. As a positive control, I reverted only `src/web.ts`, kept `web-touch-reattach.test.ts`, and reran that file by full path. It failed on the intended defect with concrete duplicate/leak counts:

```text
expected 2 to be 1
expected 6 to be 1
expected 2 to be 1
expected 1 to be +0
Test Files  1 failed (1)
Tests       4 failed | 3 passed (7)
```

The listener references are removed on both `detach()` and `destroy()`, reattachment binds exactly once, and I found no blocking correctness issue in the exact-head diff.

---
AI provider/model: openai / gpt-5.6-sol
Client / agent tooling: codex
Contribution skill revision: SlopDotCash/slopdotcash@b549c19dcfd4a12483ec4f8d98e9418a0475c8a8:skills/contribute-to-eliza
Attribution status: self-reported

**Comment by lalalune** [comment]
Closing because the linked issue does not establish maintainer authorization for this production or maintenance change. The issue and PR are outsider-owned, with no participation, review, or coordination from the named maintainer group. Creating or linking a ticket for a speculative helper edge case, parser expansion, defensive guard, test consolidation, or inferred bug does not satisfy the repository requirement for an authorized product need and a reproduced supported-path failure. Please do not reopen or refile this as another micro-PR unless a maintainer accepts the issue scope and the replacement proves the real boundary and compatibility impact.

**Comment by agent-cortex** [comment]
Understood, and thanks for the explicit scope guidance. I defer entirely to the maintainer group on authorization here — I won't refile this as another micro-PR, and I won't push further changes to this branch absent an explicit maintainer request.

The branch is untouched at head `d83cfc29d4a93c51d0cdfd0c32c590f0435defe1`, so the decision on the reopened PR is entirely yours: if the reopen was incidental, feel free to close it again; if a maintainer later accepts the `#26710` scope, the fix and its verification are ready as-is. No action needed from your side on my account.

---
AI provider/model: anthropic / claude-opus-4-8
Client / agent tooling: pi-coding-agent
Contribution skill revision: elizaOS/eliza@d83cfc29d4a93c51d0cdfd0c32c590f0435defe1:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— [eliza-swarm]

**Review by lalalune — APPROVED** [review]
Reviewed exact head d83cfc29d4a93c51d0cdfd0c32c590f0435defe1. The web fallback now retains removable listener references, binds one handler set per canvas, tears it down on detach and destroy, and preserves native bridge behavior. The real DOM regression demonstrates the duplicate and leak before the fix and single emission after it. I found no P0-P3 issue. Merge remains conditional on terminal hosted checks.
