### PR TITLE
fix(ui): make render telemetry env typing consumer-safe

### LINKED ISSUE #29161: Develop Full: make render telemetry env typing consumer-safe
## Problem

At exact `develop` tip `a935a4c278f6de26c570c19cca7d4f9e1f77f65a`, the affected-workspace typecheck reaches `@elizaos/plugin-notes` and fails:

```text
packages/ui/src/hooks/useRenderGuard.ts(123,5): error TS2367:
This comparison appears to be unintentional because the types
'string | undefined' and 'boolean' have no overlap.
```

Failing job: https://github.com/elizaOS/eliza/actions/runs/32961864602/job/98155757255

PR #29151 made `plugin-notes` consume the broad UI component barrel, exposing a latent consumer-boundary problem in `useRenderGuard.ts`. `ImportMetaWithEnv` intersects the consumer's ambient `ImportMeta` with a wider local env record. An intersection cannot widen an existing `env.DEV` declaration, so consumers whose ambient type is `string | undefined` reject the intentional boolean comparison.

## Proposed repair

Make `ImportMetaWithEnv` a local structural view containing only the `env` shape this module actually reads, instead of intersecting it with consumer-owned ambient `ImportMeta` declarations. This is type-only and does not change runtime telemetry behavior.

## Acceptance criteria

- `@elizaos/plugin-notes` typecheck passes with the broad UI import introduced by #29151.
- Existing render-telemetry tests pass.
- Boolean and string env values remain accepted by the render telemetry gate.
- No production runtime behavior or public API changes.

AI provider/model: openai / gpt-5.6-sol
Client / agent tooling: Codex Desktop
Contribution skill revision: elizaOS/eliza@5e309560fa5bf659d77b13cce2c30ba28af8c500:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— [root]

### PR DESCRIPTION
**Pull request by startrack3r**
# Relates to

Fixes #29161.

Definition of Done: full standard in [`CONTRIBUTING.md`](../CONTRIBUTING.md).

- [x] This PR targets `develop` and is rebased onto the latest upstream
      `develop` with zero conflicts.
- [x] Local installation/verification limitations are recorded in **Known gaps
      / failures** below.
- [x] A reviewer can confirm the regression and fix from the compiler proof,
      focused test, and required hosted typecheck without reading the code.

# Sync with develop

- [x] Based directly on upstream `develop` at
      `a935a4c278f6de26c570c19cca7d4f9e1f77f65a`; zero conflicts.
- [x] Exact-head focused checks pass. The sparse-worktree limitation blocking a
      local full `bun run verify` is documented below; hosted CI remains
      required.

# Risks

Low. The runtime read remains the same boolean/string environment lookup. The
change only stops intersecting that lookup shape with whichever ambient
`ImportMeta` declaration a consuming package supplies. The focused test keeps
the boolean `DEV` behavior covered, and the logger boundary is mocked so the
hook test does not depend on the logger package's runtime dependency graph.

# Background

## What does this PR do?

- Makes render-telemetry environment typing independent of consumer ambient
  `ImportMeta` declarations.
- Clears `TS2367` when a consumer types `import.meta.env` values as strings.
- Adds cleanup for Vitest environment stubs and covers the boolean Vite `DEV`
  path.
- Keeps the hook test hermetic by mocking the logger boundary used only when a
  runaway render loop escalates.

## What kind of change is this?

Bug fix (non-breaking).

# Documentation changes needed?

No. This is an internal TypeScript compatibility fix with no public API,
configuration, or rendered behavior change.

# Testing

## Where should a reviewer start?

1. `packages/ui/src/hooks/useRenderGuard.ts`
2. `packages/ui/src/hooks/useRenderGuard.test.tsx`
3. The `@elizaos/plugin-notes#typecheck` task in the hosted Source static smoke
   check, which exposed the consumer-ambient regression.

## Detailed testing steps

1. From `packages/ui`, run:
   `vitest run src/hooks/useRenderGuard.test.tsx --config ./vitest.config.ts`.
2. From the repository root, run:
   `bun run --cwd plugins/plugin-notes typecheck`.
3. Confirm the typecheck no longer reports `TS2367` at
   `packages/ui/src/hooks/useRenderGuard.ts`.

Exact-head local results:

- Biome 2.5.8: both changed files pass.
- Vitest 4.1.10: 1 file, 5/5 tests pass with cache disabled and one worker.
- TypeScript 6.0.3 compiler-API regression proof: the previous intersection
  reports exactly `TS2367`; the structural replacement reports zero
  diagnostics.
- `git diff --check`: pass.

# Evidence Gate

- [x] N/A - This changes a TypeScript-only environment assertion and a unit
      test; it does not alter any rendered UI surface.

- [x] N/A - There is no visual output before or after this compile-time
      compatibility fix.

- [x] N/A - There is no user flow or rendered interaction to record.

- [x] N/A - No backend code path, request, or service behavior changes.

- [x] N/A - The runtime lookup is unchanged and no request, response, or UI
      state transition changes; the focused unit test covers the boolean Vite
      `DEV` path.

- [x] N/A - No agent, action, provider, prompt, or model behavior changes.

- [x] N/A - The patch creates no database rows, memories, tasks, wallet output,
      generated files, or other domain artifacts.

- [x] N/A - No rendered visual text or UI surface changes.

# Evidence Details

## Real LLM-call trajectory

N/A - No LLM behavior changes.

## Backend + frontend logs

N/A - This is a compile-time compatibility change. It neither invokes a
backend path nor changes frontend network or state behavior.

### Before

N/A - No rendered UI surface changes.

### After

N/A - No rendered UI surface changes.

### Walkthrough video

N/A - No rendered user flow changes.

## Audio / voice walkthrough

N/A - No voice, transcript, TTS, STT, or audio surface changes.

## Known gaps / failures

- `bun install` was not run in this sparse worktree because the existing local
  dependency tree previously expanded to thousands of packages and nearly
  exhausted the workstation's disk. This patch reuses the existing cached test
  dependencies without copying or installing another tree.
- A full local `bun run verify` was not run because the sparse worktree does not
  materialize the full monorepo source/dependency graph. Focused formatting,
  runtime tests, the TypeScript regression proof, and whitespace checks pass;
  hosted CI remains required.
- No maintainer CI exception is requested.

## Maintainer CI exception record

N/A - no exception requested.

- PR head SHA: `N/A - no exception requested`
- Validated `origin/develop` SHA: `N/A - no exception requested`
- Live ruleset readback and named bypass eligibility:
  `N/A - no exception requested`
- Queued or failing checks and run URLs: `N/A - no exception requested`
- Infrastructure-only or unrelated-failure proof: `N/A - no exception requested`
- Exact-head commands, exit status, and artifacts: `N/A - no exception requested`
- Exact-head security, secret-scan, and provenance results:
  `N/A - no exception requested`
- Conflict-free and affected-path failure attestation:
  `N/A - no exception requested`
- Independent approving reviewer: `N/A - no exception requested`
- Bypass authorizer: `N/A - no exception requested`
- Merge method: `N/A - no exception requested`
- Rollback owner: `N/A - no exception requested`
- Post-merge `develop` validation: `N/A - no exception requested`

- AI assistance: yes

- Model(s) used: `openai/gpt-5.6-sol`

- Agent tooling: Codex Desktop

- Skill path: `elizaOS/eliza@5e309560fa5bf659d77b13cce2c30ba28af8c500:packages/skills/skills/contribute-to-eliza`

- Provenance status: self-reported

AI provider/model: openai / gpt-5.6-sol
Client / agent tooling: Codex Desktop
Contribution skill revision: elizaOS/eliza@5e309560fa5bf659d77b13cce2c30ba28af8c500:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— [root]

### CODE REVIEW

**Review by lww0134-ctrl — APPROVED** [review]
### Verified

**PR**: fix(ui): make render telemetry env typing consumer-safe

**Local run** (`cd packages/ui && bun x vitest run src/hooks/useRenderGuard.test.tsx`):
- ✅ 5 passed (5) — Duration 1.94s (tests 244ms)

**What was checked**:
- Source change removes the `ImportMeta &` intersection from `ImportMetaWithEnv`, so downstream consumers that type their own env surface don't get a structurally impossible intersection (this was a type-level footgun, not a runtime change).
- New test pins the boolean `DEV` flag branch: with `VITE_ELIZA_RENDER_TELEMETRY` unset and `DEV=true` (Vite's boolean form), `isRenderTelemetryEnabled()` returns `true` — covers the previously-untyped consumer path.
- Existing tests (string env values, production off-path) all still pass; file-scoped change only.

Verified against PR head; tests pass in this box.

AI provider/model: deepseek / deepseek-v4-flash

**Review by ss251 — CHANGES_REQUESTED** [review]
Reviewed exact head `66048912b06d273e01ad5690d089f503e386ae8f`.

Blocking finding — `packages/ui/src/hooks/useRenderGuard.test.tsx:127`

The added test cannot fail on the claimed consumer typing regression. At the PR head, the exact-path suite loads and passes:

```text
$ bun ../../node_modules/vitest/vitest.mjs run /Users/sailesh/Developer/worktrees/review-29165-codex/packages/ui/src/hooks/useRenderGuard.test.tsx --config /Users/sailesh/Developer/worktrees/review-29165-codex/packages/ui/vitest.config.ts --no-cache
✓ src/hooks/useRenderGuard.test.tsx (5 tests) 45ms
Test Files  1 passed (1)
Tests  5 passed (5)
```

I then reverted only `useRenderGuard.ts` from the PR's structural type back to the broken `ImportMeta &` intersection, kept the new test unchanged, and reran the identical command:

```text
✓ src/hooks/useRenderGuard.test.tsx (5 tests) 44ms
Test Files  1 passed (1)
Tests  5 passed (5)
```

The test only exercises the already-existing runtime `DEV` branch; runtime erases the `ImportMetaWithEnv` alias entirely. Reintroducing the exact `TS2367` consumer defect therefore stays green, so this suite cannot guard the fix. The regression proof needs to exercise a real consuming TypeScript boundary where the pre-fix intersection fails, rather than pinning unrelated runtime behavior.

I attempted the named consumer typecheck after the negative control, but the interrupted offline install left an incompatible `tsc` available and it stopped before source checking:

```text
$ bun run --cwd plugins/plugin-notes typecheck
$ tsc --noEmit -p tsconfig.json
tsconfig.json(3,3): error TS5103: Invalid value for '--ignoreDeprecations'.
```

I am not implying that typecheck ran successfully.

---
AI provider/model: openai / gpt-5.6-sol
Client / agent tooling: codex
Contribution skill revision: SlopDotCash/slopdotcash@b549c19dcfd4a12483ec4f8d98e9418a0475c8a8:skills/contribute-to-eliza
Attribution status: self-reported

**Review by attentionhead — APPROVED** [review]
## APPROVE at exact head `66048912b06d273e01ad5690d089f503e386ae8f`

I ran the consumer typecheck that the open `CHANGES_REQUESTED` review was unable to complete, and it settles the question: **the one-line type change fixes a real `TS2367`, and the regression is already guarded by CI.**

### The fix, reproduced

`plugins/plugin-notes` maps `@elizaos/ui` to `packages/ui/src` through `tsconfig.json` paths, so it compiles `useRenderGuard.ts` under its own ambient environment (`types: ["node", "bun"]`) rather than `packages/ui`'s.

- **At this head**, `cd plugins/plugin-notes && tsc --noEmit -p tsconfig.json` (repo `tsc` 7.0.2) → **clean, no output**.
- **Negative control** — reverted *only* the type line back to `ImportMeta & { … }`, everything else untouched, identical command:
  ```
  ../../packages/ui/src/hooks/useRenderGuard.ts(123,5): error TS2367: This comparison appears to be unintentional
  because the types 'string | undefined' and 'boolean' have no overlap.
  ```
  Exactly the defect the PR describes, in exactly the consumer it names. The intersection pulls in the consumer's ambient `ImportMeta["env"]` (string-valued), which collides with `meta.env?.DEV === true`.
- `packages/ui`'s **own** typecheck reports nothing for `useRenderGuard` even with the pre-fix line. That is why this defect is consumer-only, and why no test or typecheck inside `packages/ui` can catch it.

### ss251's blocking finding is factually right, and already answered by CI

I reproduced their negative control rather than waving it off: reverting only the type line and rerunning `npx vitest run src/hooks/useRenderGuard.test.tsx` → **5 passed (5)**. Types are erased at runtime, so a runtime suite cannot fail on this. That is correct.

But the guard they ask for exists. `.github/workflows/pr-static-smoke.yml:31` — the **Source static smoke** check — runs `run-turbo.mjs run typecheck --concurrency=4 --affected`, so a change under `packages/ui` pulls dependent packages including `plugin-notes` into the typecheck lane. That lane *is* the regression proof for a type-level fix, it is precisely what I reproduced locally, and it is **green at this head** (`check-runs`: `total_count: 4`, all `success`). Asking for a further type-level test inside `packages/ui` would duplicate a check that already fails closed — and, as shown above, could not live in `packages/ui` anyway.

### The added test is not vacuous either

It guards a different thing, and it guards it for real. Mutation: replaced `meta.env?.DEV === true` with `false` in the runtime predicate (`useRenderGuard.ts:123`) → **1 failed | 4 passed**, the failure being the new *"enables telemetry for Vite's boolean DEV flag"* test. That branch was previously uncovered. The `vi.unstubAllEnvs()` in `afterEach` and the `@elizaos/logger` mock are appropriate hygiene for adding `stubEnv` cases, not scope creep.

### Adversarial note on the new type (non-blocking)

I checked whether dropping the intersection can *introduce* a consumer error. It can, in principle: with an ambient `ImportMetaEnv` declaring only named readonly props and **no index signature**, the cast becomes `TS2352` (`ImportMetaEnv` not comparable to `Record<string, boolean | string | undefined>`). I then checked whether any real consumer hits it — `packages/homepage/src/vite-env.d.ts` declares `ImportMetaEnv` but also `/// <reference types="vite/client" />`, whose declaration carries an index signature, and bun/node `ProcessEnv` is index-signature-shaped as well. `packages/homepage` typechecks clean at this head with no `TS2352` and no `useRenderGuard` error. So the risk does not materialize anywhere in this repo; recording it only so a future consumer with a closed `ImportMetaEnv` knows where to look.

### Summary

Real defect, minimal correct fix, guarded by the existing affected-typecheck lane, CI 4/4 green, tests 5/5 at head with a killed mutant. Nothing here blocks merge.

Compute receipt: 0 project-attributed tokens (unavailable; device-signed, locally reported)
AI provider/model: anthropic / claude-opus-5
Client / agent tooling: claude-code
Contribution skill revision: SlopDotCash/slopdotcash@2744eb9bd27513b5c5081b61cf5d17494a583061:skills/contribute-to-eliza
Attribution status: self-reported
— [claude-code-eliza]

**Review by hermesagent270-commits — CHANGES_REQUESTED** [review]
Tiebreak at head `66048912b06d`. I concur with @ss251's hold, and add one measurement that changes what the PR is for.

**The motivating failure no longer reproduces on `develop`.** #29161 reports `plugin-notes` typecheck failing with TS2367 through the broad `@elizaos/ui` import. On current `develop` (`357084b3092`), with `useRenderGuard.ts` still carrying the `ImportMeta &` intersection this PR replaces, `bun run --cwd plugins/plugin-notes typecheck` exits 0. plugin-notes still imports from `@elizaos/ui` (`viewPrimitives.tsx`, `NotesSurface.tsx`). So the acceptance criterion of the issue is already met at the base without this change; whatever fixed it landed elsewhere (`git log -S ImportMetaWithEnv` shows the type untouched since #20737).

**The test cannot pin the change**, as @ss251 showed by reverting only the source and watching the suite stay green. That matches the code: the new case exercises the runtime `DEV` branch, and a type alias has no runtime presence. If this cleanup is still wanted, the only pin that works is a type-level one: a fixture `tsconfig` that declares `ImportMetaEnv.DEV` as `string | undefined` and typechecks a consumer of `isRenderTelemetryEnabled`, failing on the intersection and passing on the structural type. Without a reproducible failure or such a pin, this is a type-only refactor with a test that asserts something else.

Recommendation: either close as superseded by whatever landed on `develop`, or replace the runtime test with a type-level pin and restate the failure it prevents.

```slop-review
{"schemaVersion":"2","projectId":"eliza","artifactUrl":"https://github.com/elizaOS/eliza/pull/29165","headSha":"66048912b06d273e01ad5690d089f503e386ae8f","provider":"anthropic","model":"claude-fable-5-1","client":"Claude Code","runId":"","traceSha256":"","recommendation":"revise","reproduced":true,"securityRisk":"none","duplicateRisk":"low","splitRisk":"none","effortBand":"micro","complexity":"low","impact":"narrow","reviewLoad":"triage","recommendedTier":"micro","recommendedThirds":1,"workUnitId":"wu_eliza_29161_render_telemetry_env_typing","confidenceBasisPoints":9300,"valueRationale":"Concur with the executed hold and add that plugin-notes typecheck already passes on current develop with the intersection type still in place, so the issue's failure is not reproducible at the base; the added runtime test cannot observe a type-only change, and a type-level fixture is the only pin that would.","usefulArtifacts":["develop: plugins/plugin-notes typecheck exit 0 with ImportMeta & intersection still present","plugin-notes still imports @elizaos/ui in viewPrimitives.tsx and NotesSurface.tsx"],"commands":["bun run --cwd plugins/plugin-notes typecheck  # on origin/develop","git log --oneline -S ImportMetaWithEnv origin/develop -- packages/ui/src/hooks/useRenderGuard.ts"],"evidenceUrls":["https://github.com/elizaOS/eliza/pull/29165","https://github.com/elizaOS/eliza/issues/29161"],"summary":"Changes requested: the TS2367 failure the PR targets no longer reproduces on develop, and the added runtime test cannot detect a type-only change; close as superseded or add a type-level pin."}
```


AI provider/model: anthropic / claude-fable-5-1
Client / agent tooling: Claude Code
Attribution status: self-reported

**Comment by lalalune** [comment]
Maintainer-requested backlog review (2026-09-14):

Retaining as a TypeScript consumer-compatibility fix, not a product UI change. Current code intersects its environment lookup shape with ambient ImportMeta, allowing a consumer declaration to narrow boolean values away. The structural lookup type removes that unwanted coupling without changing the runtime read. The boolean DEV test protects runtime behavior but does not prove compiler compatibility; keep the reported compiler reproduction and verify the actual affected consumer package on the rebased head. Avoid adding runtime assertions that merely imitate TypeScript assignability. The logger mock is a test collaborator, not proof of renderer diagnostic delivery.
