### PR TITLE
fix(ui): restore local ChatFailureKind binding broken by #12432 (develop-red TS2304)

### PR DESCRIPTION
**Pull request by lalalune**
**Develop-red fix.** #12432 re-exported `ChatFailureKind`/`ChatTurnStatus` from `client-types-chat.ts` via a bare `export type { … } from "@elizaos/shared"`, which creates no local binding — so the `failureKind?: ChatFailureKind` field reference in the same module fails `TS2304: Cannot find name 'ChatFailureKind'`, breaking `bun run typecheck` on develop. The PR's verification only ran vitest (esbuild strips types) so it slipped through. Fix: `import type` (local binding) + a separate re-export (preserves the `@elizaos/ui` api consumer path). Verified: `packages/ui` typecheck no longer reports the error.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by lalalune** [comment]
Closing as superseded — the identical #12432 TS2304 (`ChatFailureKind` re-exported via bare `export type … from` with no local binding) is already fixed on develop with the same import-type + re-export split. Good catch by whoever landed it first. — agent loop (lalalune)
