### PR TITLE
fix(scripts): pin electrobun red-green control to the post-30643 importer

### PR DESCRIPTION
**Pull request by lumix5**
The Electrobun workspace-resolution regression control still expected an importer that moved in #30643, making the Script Tests lane fail despite reporting the correct unresolved import. Update that expected path to the live `ios-runtime-bridge.ts` importer; the control still removes the real path mapping and requires the audit to detect the broken resolution.

Validation at `5b3012daf8b1ae82c365fd4b24d06b9fa26f13d6`:

- Pinned Node 24.15.0: all six tests pass, including the real workspace red/green control.
- Pinned Bun 1.3.14: fresh install passes, including native Metal rebuild and a real 384-dimension embedding probe.
- The local Bun script suite passed five tests; its workspace control exceeded its internal 60-second timeout on the review host. The timeout log is retained alongside the successful Node result.
- Root `bun run verify` passed: 376/376 tasks, zero cached, plus final repository audits.
- All hosted checks passed in [run 33995924184](https://github.com/elizaOS/eliza/actions/runs/33995924184).
- Independently confirmed the pre-fix assertion failure in [Develop Full job 101377925035](https://github.com/elizaOS/eliza/actions/runs/33992655835/job/101377925035).

- [x] N/A - script regression assertion only; no rendered UI changes.

- [x] N/A - script regression assertion only; no rendered UI changes.

- [x] N/A - script regression assertion only; the observable result is the audit test output.

- [x] Backend logs: [full evidence file](https://github.com/lumix5/eliza/releases/download/pr-evidence-30709/30709-evidence-backend-logs.txt) and inline transcript:
```text
CI (before) run 33992655835 job 101377925035 @ develop 08f5532a22:
  (fail) historic app and Electrobun mappings are real red-green controls [12168.88ms]
  AssertionError: The input did not match the regular expression
    /platforms\/electrobun\/tsconfig\.json: unresolved @elizaos\/capacitor-bun-runtime imported by packages\/app-core\/src\/api\/ios-local-agent-transport\.ts/
  Input:
    '@elizaos/electrobun typecheck -> packages/app-core/platforms/electrobun/tsconfig.json: unresolved @elizaos/capacitor-bun-runtime imported by packages/app-core/src/platform/ios-runtime-bridge.ts'
  at packages/scripts/audit-tsconfig-workspace-resolution.test.mjs:322:10
Local repro (before) @ 08f5532a22, bun test 1.3.14 / node 24.15.0 / Linux x64:
  (fail) historic app and Electrobun mappings are real red-green controls [15855.23ms]
  5 pass / 1 fail — Ran 6 tests across 1 file
Causal chain: #30643 moved the @elizaos/capacitor-bun-runtime import from
  packages/app-core/src/api/ios-local-agent-transport.ts (grep: no matches today)
  to packages/app-core/src/platform/ios-runtime-bridge.ts (line 416);
  the control still pinned the old importer path.
AFTER FIX @ PR head 5b3012daf8b1ae82c365fd4b24d06b9fa26f13d6 (rebased on e009a5e1d1):
  bun test packages/scripts/audit-tsconfig-workspace-resolution.test.mjs
   6 pass
   0 fail
  Ran 6 tests across 1 file. [17.27s]
```

- [x] N/A - no frontend code path changes.

- [x] N/A - no prompt, model, provider, action, or agent behavior changes.

- [x] N/A - no database, memory, scheduling, wallet, or generated product state changes.

- [x] N/A - no visual surface changes.

Original author disclosure: authored by an autonomous agent — provider Z.ai, model glm-5.3-flash, client opencode 1.18.29. The device-signed attribution receipt is pending operator authorization; no attribution marker is included rather than an unsigned one.

### CODE REVIEW

**Review by OutstandingRetard — APPROVED** [review]
Scoped review of #30709 (fix(scripts): pin electrobun red-green control to the post-30643 importer).
Touches 1 file(s): `packages/scripts/audit-tsconfig-workspace-resolution.test.mjs`. Lead change `packages/scripts/audit-tsconfig-workspace-resolution.test.mjs` (+1/-1).
Matches the stated fix and is ready for maintainer merge.
No blocking concerns.

**Comment by lalalune** [comment]
Reviewed the complete diff at `5b3012daf8b1ae82c365fd4b24d06b9fa26f13d6`. This is a justified repair to an existing regression control: it still removes the actual Electrobun path mapping and requires the audit to report the unresolved import. The live importer is `packages/app-core/src/platform/ios-runtime-bridge.ts:416`.

I independently retrieved the failing Develop Full job [101377925035](https://github.com/elizaOS/eliza/actions/runs/33992655835/job/101377925035); its actual diagnostic names that new importer while the assertion expects the old transport file. This supports the change without weakening the failure contract.

The fork workflow was awaiting approval; I approved [run 33995924184](https://github.com/elizaOS/eliza/actions/runs/33995924184) after reviewing the diff, and the jobs are now running. Local validation is also running with the owning script-suite configuration. Merge remains pending completed validation and replacement of the PR body’s placeholder evidence-head marker with exact-head evidence.

**Review by agent-cortex — APPROVED** [review]
## APPROVE — verified by deep reproduction in an isolated sandbox

This one-line change fixes a genuine, currently-red required check on `develop`. I reproduced the failure and the fix end-to-end rather than reading the diff.

### Scope (matches the stated defect)
The diff touches exactly one assertion in `packages/scripts/audit-tsconfig-workspace-resolution.test.mjs:324`, updating the pinned importer in the Electrobun red-green control from `packages/app-core/src/api/ios-local-agent-transport.ts` to `packages/app-core/src/platform/ios-runtime-bridge.ts`. No other behavior is changed.

### Root cause confirmed
`#30643` (merge `9063b9adcf`, `--stat` shows `app-core/src/api/ios-local-agent-transport.ts | 1136 +-------` and `app-core/src/platform/ios-runtime-bridge.ts | 71 ++`) moved the `@elizaos/capacitor-bun-runtime` dynamic import. At the reviewed head:
- `packages/app-core/src/platform/ios-runtime-bridge.ts:416` → `const { ElizaBunRuntime } = await import("@elizaos/capacitor-bun-runtime");`
- `grep -c capacitor-bun-runtime packages/app-core/src/api/ios-local-agent-transport.ts` → `0`

The audit itself already names the *current* importer correctly; only the test's regex was stale.

### CI linkage verified
The cited failing run (33992655835, job 101377925035, `tests / Script Tests (Linux)`) failed on exactly this assertion, and it was the **only** failing test in the whole lane (every other script test file reported `0 fail`), so this single stale regex is what drove `test:scripts` to exit 1 and turned the `Develop Full` matrix red:
```
AssertionError: The input did not match the regular expression /...imported by packages\/app-core\/src\/api\/ios-local-agent-transport\.ts/.
actual: '...unresolved @elizaos/capacitor-bun-runtime imported by packages/app-core/src/platform/ios-runtime-bridge.ts'
(fail) historic app and Electrobun mappings are real red-green controls
error: script "test:scripts" exited with code 1
```

### Reproduction (sandbox, no network; bun 1.3.14)
- **Head (with fix):** `bun test packages/scripts/audit-tsconfig-workspace-resolution.test.mjs` → `6 pass / 0 fail`.
- **Base (I restored the old expectation to prove the red):** same file, `-t "historic app and Electrobun mappings"` →
```
AssertionError: The input did not match the regular expression /...src\/api\/ios-local-agent-transport\.ts/. Input:
'@elizaos/electrobun typecheck -> packages/app-core/platforms/electrobun/tsconfig.json: unresolved @elizaos/capacitor-bun-runtime imported by packages/app-core/src/platform/ios-runtime-bridge.ts'
(fail) historic app and Electrobun mappings are real red-green controls
 0 pass  1 fail
```
This is byte-for-byte the CI assertion, confirming the local repro matches the lane failure and that the fix flips red→green.

### Semantics preserved (not masking a regression)
The control still deletes the `@elizaos/capacitor-bun-runtime` path mapping from the Electrobun tsconfig and still asserts the audit *reports the unresolved import*. The audit continues to detect the violation; only the human-readable importer path in the message changed because the source moved. The regex is asserting the audit's genuine, correct output — nothing is weakened.

### Probed beyond the diff
- Grepped for other stale `ios-local-agent-transport` references. The only other hit, `packages/scripts/__tests__/scenario-runner-typecheck-graph.test.ts:17`, points at `packages/ui/src/api/ios-local-agent-transport.ts`, a *different* file that still exists — not stale.
- No other `imported by` assertion in the audit test references a moved file.

### Notes (non-blocking)
- Branch is rebased onto current `origin/develop` (`e009a5e1`), which is also the reviewed base — no drift.
- Evidence rows are appropriately `N/A` for a script-side test-expectation change; per this repo's review rubric provider/model disclosure is optional, so the author's prose-only agent disclosure (no machine marker) is acceptable for the code verdict — though note the repo's "Contribution comment attribution" gate may still require a marker before merge; that is an author action, not a code defect.

No correctness, security, or test-integrity gap found. This unblocks the required Script Tests (Linux) lane.

---
AI provider/model: anthropic / claude-opus-4-8
Client / agent tooling: pi-coding-agent
Contribution skill revision: elizaOS/eliza@df903a84be3565efbeac07fc49f398623178de23:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— [eliza-swarm]

**Review by lalalune — APPROVED** [review]
Reviewed exact head 5b3012daf8b1ae82c365fd4b24d06b9fa26f13d6. The assertion still exercises real broken Electrobun workspace resolution and now names the actual importer; independently confirmed the upstream failure. Six Node tests pass, fresh pinned install and native embedding probe pass, full root verify passes 376/376 with zero cached tasks, hosted checks pass, and the exact-head evidence gate passes. The local Bun timeout is disclosed with its original output.
