### PR TITLE
fix(core): build the revision copy without Array#with

### PR DESCRIPTION
**Pull request by lalalune**
# Relates to

Refs #16021. Fix-forward for a workspace typecheck break introduced by #23365.

# Contribution provenance

- AI assistance: `yes`

- Model(s) used: `anthropic/claude-fable-5`

- Agent tooling: `Claude Code`

- Skill path: `N/A - no contribution skill used`

- Provenance status: `self-reported`

# Sync with develop

- [x] Branched from latest `origin/develop`; zero conflicts.

# Risks

Low. One expression rewritten to an equivalent copy; no behavior change.

# Background

## What does this PR do?

`replaceDocumentRevision` in `packages/core/src/database/inMemoryAdapter.ts` used `Array.prototype.with`, an ES2023 method. `packages/agent/tsconfig.json` sets `"target": "ES2022"` and no explicit `lib`, so TypeScript resolves its lib to ES2022, where that method has no declaration:

```
../core/src/database/inMemoryAdapter.ts(924,39): error TS2550: Property 'with' does not exist on type 'Memory[]'.
```

That breaks `bun run --cwd packages/agent typecheck` on develop today. This builds the copy-on-write array by hand (`slice()` then index assignment) so the code is independent of any consumer's target, and records the constraint in a comment so the method is not reintroduced.

## What kind of change is this?

Bug fix (build/typecheck regression).

# Testing

`plugins/plugin-inmemorydb` `document-list.test.ts` at this head: **7/7 passed** — the suite that covers `replaceDocumentRevision`'s atomic swap and read barrier.

# Evidence Gate

- [x] N/A - in-memory adapter internals, no rendered UI.

- [x] N/A - in-memory adapter internals, no rendered UI.

- [x] N/A - no interactive flow.

- [x] N/A - the failure is a compile-time diagnostic, quoted above; the test receipt covers runtime behavior.

- [x] N/A - no frontend path.

- [x] N/A - no model/prompt/action behavior changes.

- [x] N/A - document revision rows are asserted directly by the suite above.

AI provider/model: anthropic / claude-fable-5
Client / agent tooling: Claude Code
Contribution skill revision: elizaOS/eliza@7c4226d710c31571caaaf4472af5bc95bd75a274:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— [core-inmemory]

### CODE REVIEW

**Comment by lalalune** [comment]
Post-merge source audit at exact head `93fa73d2c0bcd787812c57d408dcd3be3f1932e2`: retain. Replacing `list.with(index, replacement)` with `const next = list.slice(); next[index] = replacement` preserves the intended copy-on-write generation and removes the ES2023 lib dependency for ES2022 consumers. The commit was exactly one commit atop then-current develop and the runtime semantics are equivalent. It was nevertheless self-merged with all hosted checks cancelled/queued and no independent approval; the focused document-revision test plus core/agent typechecks should still be rerun on the merged develop snapshot, but no corrective production change is indicated.
