### ISSUE TITLE
test(dev): lock source-conditioned imports across every Node-backed Vite entrypoint

### ISSUE THREAD

**Issue by lalalune** [elizaOS/eliza#16964]
## Release blocker

Exact develop candidate `a71c622ac20d7e57e88b428874ba8a56478a3716` fails both Dev Smoke jobs after #16893 moved Vite from Bun to Node.

Both `bun run dev onboarding chat` and `Vite HMR dependency-level smoke` fail before Vite binds its port:

```text
Error [ERR_MODULE_NOT_FOUND]: Cannot find module
packages/cloud/routing/src/features.js
imported from packages/cloud/routing/src/index.ts
```

`packages/app/scripts/run-ui-playwright.mjs` intentionally adds `NODE_OPTIONS=--conditions=eliza-source` so Playwright can collect workspace TypeScript on a clean install. The Node-backed Vite child inherits that condition, resolves `@elizaos/cloud-routing` to `src/index.ts`, then plain Node cannot map the package's NodeNext `./features.js` specifier to `features.ts`. `node --import tsx` resolves the same graph successfully while retaining Node as the runtime.

## Acceptance criteria

- Keep the Vite dev server under Node (no `process.versions.bun`).
- Start every app development Vite entrypoint with the TypeScript loader needed by source-conditioned workspace exports.
- Add regression coverage for dashboard/shared-worktree and direct package dev commands.
- Prove both Dev Smoke jobs pass from a clean source-conditioned install.
- Run package tests, typecheck/lint, error-policy ratchet, and repo verify as appropriate.

## Failing evidence

- Develop push run: https://github.com/elizaOS/eliza/actions/runs/29989484242
- HMR job: https://github.com/elizaOS/eliza/actions/runs/29989484242/job/89149557758
- Onboarding job: https://github.com/elizaOS/eliza/actions/runs/29989484242/job/89149557761
- Frozen promotion blocked: #16962

**Comment by lalalune** [comment]
`645d216099129d74e2d7c4ae66e16b46c9231d8f` fixes the underlying loader defect on develop: every dev Vite path is now Node plus `--import tsx`, and the exact-commit Dev Smoke run no longer reports the source-conditioned `@elizaos/cloud-routing` module-not-found failure. The HMR lane is green (run 29991063870).

I’m keeping this open for the remaining acceptance proof: that same run's onboarding-chat lane timed out after 420 seconds waiting for Playwright webServer readiness, so we still do not have both Dev Smoke jobs green. PR #16986 adds the right real import/direct-entrypoint regression in commit `060b0f6`, but it also carries unrelated app-interaction and visual-budget changes and is currently unstable.

Please split or narrow that PR to the loader regression, merge it, then attach a clean source-conditioned run where both Dev Smoke jobs pass, plus scoped test/typecheck/lint/error-policy-ratchet/verify output. No rendered UI evidence is required for the dev-tooling-only change; any retained UI/aesthetic changes require their own issue and full app-audit evidence.

**Comment by lalalune** [comment]
Closing as fixed: commit 645d216099129d74e2d7c4ae66e16b46c9231d8f moved every dev Vite entrypoint to Node with --import tsx and the exact-commit Dev Smoke lanes went green (see the run links in the last comment), and #16986 landed the Node-backed Vite gate hardening. If a source-conditioned resolution failure recurs in a Dev Smoke run, please reopen with the new run link.
