### PR TITLE
fix(cloud): reserve app inference credits upfront

### LINKED ISSUE #10857: money: monetized-app (X-App-Id) inference has no atomic upfront credit hold — concurrent requests overspend the org balance
## Confirmed via adversarial audit (full code trace)

**Severity:** high (money — concurrent overspend, platform absorbs the loss; requires the X-App-Id monetized-apps surface live)

### Scenario
An org with $1 balance sends N concurrent POST /api/v1/messages with header X-App-Id=<monetized app>, each costing ~$1. Every request calls appCreditsService.checkBalance() (a plain org-balance READ, no lock, no deduct) which returns sufficient for all of them, so all N are served by the model. The actual charge only happens later in onFinish -> appCreditsService.reconcileCredits({estimatedBaseCost: 0, actualBaseCost: totalCost}); reserveAndDeductCredits is atomic, so only ~1 request's charge succeeds and the other N-1 hit the 'Insufficient org balance for additional charge (platform absorbing loss)' branch (app-credits.ts:688-700). Net: the user gets N paid completions for $1 and the platform eats the rest. The org-credit (non-app) path does not have this hole because it reserves atomically upfront via reserveCredits()/reserveAndDeductCredits(), which serializes concurrent requests and returns 402 when the balance can't cover the hold.

### Location
`packages/cloud/api/v1/messages/route.ts:631 (checkBalance + createAnonymousReservation at :649; estimatedBaseCost:0 at :647) with the loss absorbed in packages/cloud/shared/src/lib/services/app-credits.ts:688-708`

### Fix
Give the monetized-app path the same atomic upfront hold as the org path: instead of a read-only checkBalance + no-op anonymous reservation, deduct the estimated marked-up cost up front via reserveAndDeductCredits (or a real reservation seeded with estimatedBaseCost = the estimated cost), then reconcile estimate->actual in onFinish. That way N concurrent app-inference requests are serialized on the org balance and the surplus ones get a clean 429/402 instead of being served and absorbed by the platform.

### Verification
Verified end-to-end. The monetized-app inference branch in packages/cloud/api/v1/messages/route.ts:619-649 performs only a read-only advisory balance check: appCreditsService.checkBalance() (app-credits.ts:777-802) does findById(org) then `balance >= requiredAmount` with no row lock, no FOR UPDATE, and no deduct. It then sets estimatedBaseCost:0 (route:647) and uses creditsService.createAnonymousReservation() (credits.ts:1042-1048), which returns reservedAmount:0 and a no-op reconcile — so nothing is held upfront, not even a partial estimate. The real charge is deferred to onFinish -> reconcileCredits({estimatedBaseCost:0, actualBaseCost:totalCost}) (route:829/:983). Because estimatedBaseCost is 0, baseCostDifference equals the full actual cost and hits the atomic CHARGE branch (reserveAndDeductCredits, FOR UPDATE at credits.ts:465). Under N concurrent POST /api/v1/messages with X-App-Id for the same org, all N pass the lock-free checkBalance and are served by the model; then only ~1 reconcile debit succeeds and the other N-1 fall into app-credits.ts:688-700 "Insufficient org balance for additional charge (platform absorbing loss)" returning adjustedAmount:0. The user obtains N paid completions for ~1 charge and the platform silently eats the rest. The contrast in the finding is accurate: the org-credit else-branch (route:652) reserves atomically upfront via reserveCredits -> reserve -> reserveAndDeductCredits (FOR UPDATE) and throws InsufficientCreditsError -> 429, serializing concurrency; the app path bypasses that entirely. Refutation attempts failed — there is no upstream atomic hold, the race window spans the whole inference call, and the exploit is self-inflictable by an org owner and repeatable (keep balance near zero, fire concurrent bursts), yielding unbounded, though single-org-scoped, platform loss. Distinct from the excluded already-fixed items (v1/chat + embeddings reservation *leaks*, x402, payouts, webhook loss); this is a never-reserved TOCTOU overspend. Severity high rather than critical because it requires the X-App-Id monetized-apps surface to be live and the blast radius per burst is bounded (though repeatable) and attacker-account-scoped.

### PR DESCRIPTION
**Pull request by lalalune**
Fixes #10857

## Summary
- Added `AppCreditsService.reserveInferenceCredits()` to atomically debit the estimated app inference cost before model work and reconcile estimate-to-actual through the existing app-credit ledger.
- Updated monetized `X-App-Id` paths in `/v1/messages` and `/v1/chat/completions` to use the upfront app reservation instead of a read-only balance check plus anonymous reservation.
- Kept creator earnings idempotent without suppressing legitimate overage earnings by using separate stable charge-phase keys for estimate and reconcile adjustments.

## Evidence
- `bunx biome check --write packages/cloud/shared/src/lib/services/app-credits.ts packages/cloud/shared/src/lib/services/__tests__/app-credits-ledger.test.ts packages/cloud/api/v1/messages/route.ts packages/cloud/api/v1/chat/completions/route.ts`
- `bun test packages/cloud/shared/src/lib/services/__tests__/app-credits-ledger.test.ts` — 25 tests passed
- `bun test packages/cloud/api/__tests__/messages-iac-fast-path.test.ts` — 2 tests passed
- `rg -n "checkBalance\(|calculateCostWithMarkup\(|createAnonymousReservation\(|estimatedBaseCost: 0|No upfront debit" packages/cloud/api/v1/messages/route.ts packages/cloud/api/v1/chat/completions/route.ts` — no stale advisory-check or zero-estimate app-credit path remains; remaining anonymous reservations are non-app optimistic fallbacks

## Blocked / Not Run
- `bun test packages/cloud/api/__tests__/chat-completions-streaming-credit-leak.test.ts` is blocked in this worktree by an incomplete linked dependency tree, ending at missing `redis` from `packages/cloud/shared/src/lib/cache/client.ts`.
- `bun run --cwd packages/cloud/shared typecheck` and `bun run --cwd packages/cloud/api typecheck` are blocked by missing top-level dependency/type links in the local install (`@cloudflare/workers-types`, `redis`, `uuid`, `viem`, `decimal.js`, and others). Details are in `.github/issue-evidence/10857-app-credit-hold.md`.

## Evidence Artifact
- `.github/issue-evidence/10857-app-credit-hold.md

### CODE REVIEW

**Comment by NubsCarson** [comment]
Dupe-reconcile with my #10909 (same #10857): **yours is the more complete impl** — it covers `/v1/chat/completions` too (I only did `/v1/messages`) and handles the creator-earnings estimate-vs-reconcile key separation cleanly via `reserveInferenceCredits`. Recommend this one lands.

One gap worth closing: the tests here **mock** `reserveAndDeductCredits` (assert it's called), so they don't prove the actual property — that concurrent requests can't overspend. My #10909 added a **real-PGlite concurrency test** to `credits-deduct-guard.test.ts` (8 concurrent $0.30 debits on a $1 balance → exactly 3 win, balance never goes negative). Happy to port just that test onto this branch so the overspend-prevention is proven end-to-end, not mocked. Closing #10909 in favor of this.

**Review by NubsCarson — COMMENTED** [review]
Deep review (I filed #10857) — **this closes the core attack correctly**. Traced the full money path at the PR head; everything below verified against the actual code, not just the diff:

✅ **The hold is truly atomic**: `reserveInferenceCredits` → `deductCredits` → `creditsService.reserveAndDeductCredits` (the same row-locked org-ledger debit the org path uses), replacing the lock-free `checkBalance` + no-op `createAnonymousReservation`. N concurrent requests can no longer all pass an advisory check.
✅ **Every terminal path settles exactly once**: the app reservation flows through the shared `createCreditReservationSettler` (single settle-promise = idempotent), route catch + stream/non-stream error paths call `settle(0)` → full refund **and** proportional creator-earnings reversal (the #10909 refund leak shape is structurally excluded here).
✅ **Earnings can't double-mint but legit overage still pays**: distinct `:estimate` / `:reconcile` idempotency keys — verified in the unit tests.
✅ **`instanceof InsufficientCreditsError` is safe**: routes import it from `ai-billing`, which re-exports the *same class object* from `./credits` (ai-billing.ts:25,550) — worth knowing since your worktree typecheck was blocked.
✅ **Post-debit accounting failure compensates the charge** before rethrowing — no orphaned hold.
✅ `/v1/messages` hold is sized to `request.max_tokens` (required by the Anthropic schema) — actual output can't exceed the estimate basis, so overage there is input-estimate noise only.

⚠️ **One residual worth fixing (pre-merge or fast-follow): `/v1/chat/completions` under-holds when the client omits `max_tokens`.** `estimatedOutputTokens = effectiveMaxTokens ?? request.max_tokens ?? 500`, and `computeEffectiveMaxTokens` returns `undefined` for non-reasoning models without a requested cap — so the hold covers ~500 output tokens while the provider can emit its model max (8–32k). The overage is charged at reconcile but can land as `uncollected_overage`, so N concurrent no-`max_tokens` requests still aggregate-overspend past the balance — the #10857 attack survives in weakened form on this one route. Suggested fix, consistent with your own #10932 (app-chat reserves against max_tokens): when the client omits `max_tokens`, estimate the hold against the model's max output (or a config ceiling) instead of 500.

📝 Test note: the new suite mocks `reserveAndDeductCredits`, so it pins the wiring, not DB atomicity — fine since atomicity lives in the pre-existing proven primitive, but the real-PGlite 8-concurrent-requests test offered in #10909's closing comment would make the end-to-end guarantee regression-proof. Worth porting.

With the `?? 500` estimate fixed I'd approve outright.

**Comment by lalalune** [comment]
Rebased on develop — **now mergeable** (was DIRTY). The conflict was in the two app-inference routes (`chat/completions`, `messages`): develop's merged #10423 added a `reconcileCredits` idempotencyKey inline, while this branch **restructures** the app-credits flow to reserve upfront and settle inside `appCreditsService` (the route-level reconcile blocks moved into the service, where the idempotencyKey is preserved). Resolution: took this branch's restructure at all four conflict hunks; `app-credits.ts` auto-merged both changes. Gate: `app-credits-ledger.test.ts` + `credits-reconcile.test.ts` **40/40 green** (no double-charge, idempotency intact) and both routes typecheck clean. UNSTABLE = CI backlog only.

**Comment by NubsCarson** [comment]
Adversarially reviewed this against #10857 (I filed it) with a refute-twice verification pass — **the hole is genuinely closed**. The upfront hold is a real atomic debit (`reserveAndDeductCredits`'s single CTE with `SELECT … FOR UPDATE` + conditional `WHERE current_balance >= amount`), applied to **both** previously-vulnerable routes (`/v1/messages` + `/v1/chat/completions`), streaming and non-streaming; every path settles or refunds the hold (success reconciles estimate→actual, error/abort/outer-catch settle(0)-refunds, first-call-wins settler prevents double-settle); `billUsage` doesn't double-charge when a reservation is passed; creator earnings use distinct `:estimate`/`:reconcile` keys so overage isn't deduped away. `/v1/chat` and `/v1/responses` never had the X-App-Id app-credit path. 👍 for merge from my side — with one regression worth fixing first:

## MED — $0 estimate now 500s monetized-app inference (confirmed by 2 independent refuters)

When the estimated cost is exactly **$0** — a model missing from the pricing catalog (a documented, deliberately-tolerated condition: `calculateTextCostFromCatalog` bills a catalog miss at `Decimal(0)` *by design*, its comment citing the prior 500 this avoided) or a genuinely $0-priced model — the new path feeds `amount: 0` into `reserveAndDeductCredits`, which throws `Error("Amount must be positive")` (credits.ts:453-455). That throw sits **outside** `deductCredits`' try/catch (try begins app-credits.ts:508), is **not** an `InsufficientCreditsError`, so both routes re-throw → **500**. Pre-fix the same request was served (checkBalance vs $0 = sufficient, reconcile no-op), and the org path avoids it by flooring: `reservedAmount = Math.max(estimatedCost * COST_BUFFER, MIN_RESERVATION)`.

**Fix:** floor the app hold at `MIN_RESERVATION` (or short-circuit a $0 estimate to a no-hold path) before calling `reserveAndDeductCredits`. Fails-closed today (no money loss), so this is availability, not integrity.

## LOW — every `deductCredits` failure is mapped to `InsufficientCreditsError`

`reserveInferenceCredits` unconditionally does `throw new InsufficientCreditsError(deduction.totalCost, deduction.newBalance, …)` (app-credits.ts:394-400), but `deductCredits` also returns `success:false` for "App not found" (app-credits.ts:443-453) and "User has no organization" (app-credits.ts:469-480). Those surface to the client as a bogus 402/429 "Insufficient cloud credits. Required: $X" with `newBalance:0`. Low likelihood (routes pre-validate the app + org), but the mapping masks the true error — worth switching on `deduction.message`.

(Not approving/merging — money path is your merge call.)

**Comment by lalalune** [comment]
Post-merge follow-up: **#11008** closes the two gaps flagged in review here.

**1. The real-PGlite concurrency test (as offered from #10909) is now ported.** Two layers, nothing mocked on the money path:
- `credits-deduct-guard.test.ts`: verbatim #10909 port — 8 concurrent $0.30 `reserveAndDeductCredits` debits on a $1.00 balance → exactly 3 win, 5 fail closed, balance never negative, exactly 3 debit rows.
- new `app-credit-hold-concurrency.test.ts`: drives the REAL `appCreditsService.reserveInferenceCredits` end-to-end against PGlite (`pushSchema` real Drizzle schema) — 8 concurrent holds → 3 win + 5 `InsufficientCreditsError`, `settle(0)` refunds the full hold, and the `:estimate`/`:reconcile` phase keys are proven against the real redeemable-earnings dedupe (overage still mints; a reconcile retry does not double-credit — the property that subsumes #10873's per-request earnings dedupe).

**2. This PR landed a test regression on `develop`, fixed in #11008:** `chat-completions-streaming-credit-leak.test.ts` calls the exported `handleStreamingRequest` positionally and still passes the removed `appCreditsInfo` arg, shifting `30_000` into the settler slot — 3 of its 4 tests currently fail on `develop` (`TypeError: settleReservation is not a function ('settleReservation' is 30000)`) and the file typechecks red. Invisible here because this PR's worktree couldn't run cloud/api tests. Dropping the stale arg restores 4/4 green.

Verified on `develop` tip cc911aa6a8c: shared suites 38/38 + 17/17 adjacent, cloud/api route suites 29/29, biome clean, `cloud/shared` typecheck clean, `cloud/api` typecheck down to only pre-existing develop errors.

(Housekeeping: while preparing a rebase of this branch it was merged and its ref deleted; a push transiently recreated `fix/10857-app-credit-hold`, which has been deleted again. The work moved to `test/10857-real-pglite-credit-hold-proof` → #11008.)
