### ISSUE TITLE
Error after updating to latest version

### ISSUE THREAD

**Issue by sonatonagems** [elizaOS/eliza#2871]
I am getting the following error. Would like to know how to resolve this: 
(node:23019) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23019) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

node:internal/modules/run_main:104
    triggerUncaughtException(
    ^
Error: Cannot find module '/home/sonat/eliza/agent/node_modules/@elizaos/adapter-pglite/dist/index.js' imported from /home/sonat/eliza/agent/src/index.ts
    at finalizeResolution (/home/sonat/eliza/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:352:11)
    at moduleResolve (/home/sonat/eliza/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (/home/sonat/eliza/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /home/sonat/eliza/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/home/sonat/eliza/node_modules/ts-node/src/esm.ts:168:34)
    at /home/sonat/eliza/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/home/sonat/eliza/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/home/sonat/eliza/node_modules/ts-node/src/esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:240:30)

Node.js v23.5.0

**Comment by naiveai-dev** [comment]
Same happened in Node 23.3.0.
Node 23.6.0 also seems like not compatible with 0.1.8.
It works fine in 0.1.7 for some reason

**Comment by tcm390** [comment]
Hi @naiveai-dev, could you kindly pull the latest develop branch and check if the issue is resolved?

**Comment by naiveai-dev** [comment]
Thanks @tcm390 . But sadly, I tried but it still got an error. Do I need to delete the existing version to run the latest version of Eliza without errors? I'll proceed this way first and check if the issue is resolved.

**Comment by sonatonagems** [comment]
@tcm390 im still getting an error after pulling the latest develop branch: 

(node:883) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:883) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

node:internal/modules/run_main:104
    triggerUncaughtException(
    ^
Error: Cannot find module '/home/sonat/eliza/agent/node_modules/@elizaos/adapter-pglite/dist/index.js' imported from /home/sonat/eliza/agent/src/index.ts
    at finalizeResolution (/home/sonat/eliza/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:352:11)
    at moduleResolve (/home/sonat/eliza/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (/home/sonat/eliza/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /home/sonat/eliza/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/home/sonat/eliza/node_modules/ts-node/src/esm.ts:168:34)
    at /home/sonat/eliza/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/home/sonat/eliza/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/home/sonat/eliza/node_modules/ts-node/src/esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:240:30)

Node.js v23.5.0

**Comment by naiveai-dev** [comment]
same here. Still got an error. Is Node.js v23.6.0 not supported in Eliza os?

**Comment by AIFlowML** [comment]
23.6.0 is not yet supported
Can you run on a clean develop with the suported version please and report back to me ?
Also, adapter-pglite missing. Did you perform and clean install build ? 

Tnks a lot.

**Comment by naiveai-dev** [comment]
@AIFlowML Thanks. 23.5.0 works fine after I run on a clean develop. I think [quick start](https://elizaos.github.io/eliza/docs/quickstart/) 
Prerequisites should be changed with Node specific node version. (ie. under 23.5.0 supported) 
My team members assumed they needed the most recent version of Node.js, so they all updated their installations to Node.js 23.6.0.

**Comment by sonatonagems** [comment]
@AIFlowML sorry I'm a complete beginner. how do i perform and clean install build? Is it just i do pnpm clean and pnpm build?

**Comment by sonatonagems** [comment]
@AIFlowML i got it fixed thank you
