### ISSUE TITLE
[plugin-elizacloud] dist packaging broken: exports resolve to dist/node/index.d.ts re-exporting nonexistent ../index.node

### ISSUE THREAD

**Issue by lalalune** [elizaOS/eliza#15779]
Found while authoring the keyless scenario for cluster 1 of #15759 (PR #15778):

`@elizaos/plugin-elizacloud`'s published exports resolve `.` to `dist/node/index.d.ts`, which re-exports a **nonexistent** `../index.node` — so `import("@elizaos/plugin-elizacloud")` fails under default node conditions (no `eliza-source`). The Zero-Key corpus lane and other test lanes survive only because they run with `--conditions eliza-source` (resolving to `src`), so the breakage is latent: any consumer importing the built package (production packaging, a lane without the source condition) hits it.

Fix direction: correct the package's build output/exports so the dist entry actually exists (or the `.` export points at the real built entry), and add a lane that imports the BUILT package under default conditions so this class can't regress silently — the same dist-vs-source resolution class as #15764 and the plugin-app-control `bun` condition in #15721.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by lalalune** [comment]
CLAIMING: verify the default-condition built-package export fix in PR #15801, resolve any remaining CI findings, and hand it off ready for human review.

**Comment by lalalune** [comment]
Verified this empirically before fixing, and the headline claim does **not** reproduce — but two real adjacent defects turned up. Fix + the requested regression lane are in PR #15832.

## What I tested

1. **Fresh `bun run build.ts`** (current `develop`): `dist/node/index.node.js` (runtime entry), `dist/node/index.d.ts` (shim), **and** the shim's target `dist/index.node.d.ts` are all emitted. The target comes from the tsc declaration pass (`tsconfig.build.json` includes `src/index.node.ts`, `rootDir src → outDir dist`), and the build driver aborts *before* writing shims if tsc fails — so no current build can produce a dist where the shim exists but its target doesn't.
2. **Published `2.0.3-beta.7` tarball** (`npm pack`): same three files all present.
3. **Runtime import under default node conditions** (no `--conditions eliza-source`), against the built package:
   ```
   IMPORT OK under default node conditions
   default export name: elizaOSCloud
   named exports: 70
   resolved from: .../dist/node/index.node.js
   ```
   Mechanically, `import()` never touches `dist/node/index.d.ts` at all — the `types` condition only participates in TypeScript resolution; Node resolves `.` → `node` → `import` → `./dist/node/index.node.js`.

What the lane most likely hit instead: in a fresh `--ignore-scripts` checkout **dist doesn't exist yet**, so the default-condition import fails with `Cannot find module '…/dist/node/index.node.js'` — a build-orchestration gap, not broken exports. (Even with this plugin built, the import still fails if sibling workspace dists — `@elizaos/shared`, `@elizaos/cloud-sdk` — aren't built; also orchestration, not packaging.)

## What IS broken (fixed in #15832)

- **NodeNext type resolution**: the shims re-export through extensionless specifiers (`'../index.node'`), which TS `node16`/`nodenext` rejects → TS2307 for built-package TS consumers. Fixed with explicit-`.js` specifiers.
- **Windows dist pollution**: `Bun.Glob.scanSync` yields backslash paths on win32, so every subpath filter in `build.ts` silently failed — dist gained the vite-only components and duplicate root entrypoints on Windows builds. Fixed by normalizing separators.
- **Regression lane**: new `__tests__/dist-packaging.test.ts` asserts every exports-referenced dist file exists, shims are NodeNext-safe with on-disk targets, and a child Node process under **default conditions** resolves the bare package name to the built entry — the lane this issue asked for, targeting the same dist-vs-source class as #15764/#15721.

Side finding while proving the published package installable: external `npm install @elizaos/plugin-elizacloud@beta` fails outright because `@elizaos/registry` is in the published dependency graph but has never been published to npm — filing that separately.

Leaving this open to close via #15832.
