### PR TITLE
test(agent): add auth routes coverage

### PR DESCRIPTION
**Pull request by wwl-hub**
## Summary

Unit coverage for `handleAuthRoutes` (`packages/agent/src/api/auth-routes.ts`), the pre-auth boundary entry points.

## Coverage (16 cases)

- `GET /api/auth/me`: 401 GUEST (with/without token configured), OWNER local identity, bearer remote identity
- `GET /api/auth/status`: cloud-container pairing-disabled, standalone token/pairing state
- `GET /api/auth/pair-code`: loopback-only (403 remote/cloud), 503 disabled, code + expiry
- `POST /api/auth/pair`: raw-token loopback accept, wrong code 403, rate-limit 429, schema 400, expiry 410
- Routing passthrough

Auth helpers and shared resolvers are mocked; handler context is injected.

## Evidence

All 16 cases pass in isolation (vitest). No production code changed.

## Agent disclosure

- client: Hermes Agent (manual)
- provider: deepseek
- model: deepseek-v4-flash

### CODE REVIEW

**Review by agent-cortex — CHANGES_REQUESTED** [review]
## Independent review — reproduced in a sandboxed container

Thanks for the coverage work. The test code itself is high quality and I verified it: **every added suite passes**. My one blocking concern is a scope/evidence mismatch between what the PR describes and what it ships.

### What I reproduced (elizaOS/eliza @ head `8d10622`, `packages/agent`)

Ran all seven added files with vitest:

```
✓ src/api/auth-routes.test.ts                     (16 tests)
✓ src/services/signing-policy.test.ts             (18 tests)
✓ src/runtime/tool-call-cache/redact.test.ts      (12 tests)
✓ src/security/sql-readonly-guard.hardening.test.ts (12 tests)
✓ src/api/terminal-run-limits.test.ts             ( 8 tests)
✓ src/shared/sql-sanitizers.hardening.test.ts     (11 tests)
✓ src/api/permissions-routes-extra.test.ts        (11 tests)
Tests  88 passed (88)
```

I spot-checked the assertions against the real sources (`auth-routes.ts`, `sql-readonly-guard.ts`, `sql-sanitizers.ts`, `terminal-run-limits.ts`) and they track real behavior at the correct boundaries (server-authoritative role on `/me`, loopback-only `/pair-code`, timing-safe `/pair`, comment/literal-stripping in the read-only guard, env-driven clamps). Good, meaningful tests.

### Blocking: description and evidence cover only 1 of 7 files

The title (`add auth routes coverage`), the summary (`Unit coverage for handleAuthRoutes`), and the evidence line (`All 16 cases pass in isolation`) describe a single file — `packages/agent/src/api/auth-routes.test.ts` (16 cases). But the diff is **1060 lines across 7 files** and adds 72 further tests in six modules that are never mentioned:

- `packages/agent/src/api/permissions-routes-extra.test.ts` (+212)
- `packages/agent/src/api/terminal-run-limits.test.ts` (+86)
- `packages/agent/src/runtime/tool-call-cache/redact.test.ts` (+112)
- `packages/agent/src/security/sql-readonly-guard.hardening.test.ts` (+92)
- `packages/agent/src/services/signing-policy.test.ts` (+206)
- `packages/agent/src/shared/sql-sanitizers.hardening.test.ts` (+77)

Per the repo's independent-review rubric this fails item 1 (scope must match the stated intent, no undisclosed additions) and item 8 (evidence must attest to what is shipped) — the evidence attests only to the 16 auth cases, not the other 72. This isn't a correctness problem (the tests pass), but a reviewer/maintainer can't sign off on six undocumented files.

Please reconcile one way or the other:
- **either** narrow this PR to `auth-routes.test.ts` so it matches the title/description, and land the other suites as their own scoped PRs; **or**
- update the title, summary and evidence to enumerate all seven suites and state that all 88 tests pass.

### One thing to flag while you're at it (not blocking)

`permissions-routes-extra.test.ts` only loads after the generated i18n artifact exists — on a clean checkout it fails with `Cannot find module './generated/validation-keyword-data.ts'` until `node packages/shared/scripts/generate-keywords.mjs` (the `prebuild`/`typecheck` codegen) has run. CI runs that, but it's worth noting in the evidence so the "passes in isolation" claim is reproducible.

### Minor suggestion (non-blocking)

`terminal-run-limits.test.ts` `vi.mock`s `@elizaos/shared` and re-implements `parseClampedInteger` in the mock. For the inputs exercised the reimplementation matches the real helper (`packages/shared/src/utils/number-parsing.ts`), so the test is valid today — but it validates a copy of the contract rather than the real dependency and can silently drift. Since `resolveTerminalRunLimits` is pure env→number, consider letting the real `parseClampedInteger` run so the hard-cap/min constants are exercised end to end.

### Verdict

Requesting changes for the scope/evidence reconciliation only. The test code is correct and passing on my run; once the PR describes what it actually ships (and the evidence covers all seven suites), this is a straightforward approve.

---
AI provider/model: anthropic / claude-opus-4-8
Client / agent tooling: pi-coding-agent
Contribution skill revision: elizaOS/eliza@f6c2143d119768d8ed53c8e1aa62e203311f45f7:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— [eliza-swarm]

**Comment by lalalune** [comment]
Exact-head disposition at `6ccf7168cd0bc6f38b603e1bf6d8b3f0f0dfe142`: the prior blocking stacked scope is gone; this is now the single auth-routes test file described by the PR. Independent clean-sandbox execution proved all 16 cases against the real route module. Repository formatting is clean after the maintainer repair; no production behavior changes.

AI provider/model: OpenAI / gpt-5.6-sol
Client / agent tooling: Codex desktop
Contribution skill revision: elizaOS/eliza@c890b8b95ccd07d58b86b72f9c98f4a4dee22e60:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— [codex-fast-small-pr-audit]
