### ISSUE TITLE
[P0-followup] bun run verify still broken after #13640 — type-safety-ratchet baseline drift on develop

### ISSUE THREAD

**Issue by 0xSolace** [elizaOS/eliza#13658]
## Repro (pristine develop, post-#13640)

```
bun run audit:type-safety-ratchet
```

fails on pristine `develop`:

- `as unknown as`: **75 current > 73 baseline**
- `?? []` (core/agent/app-core): **582 current > 581 baseline**

So `bun run verify` still dies at step 1/2 (`audit:type-safety-ratchet` is the first command in the `verify` chain) even after #13640 lands.

## Where the drift came from

Diffed classifier findings against the last baseline commit (8838ad9df68, the #12480 merge that last touched `type-safety-ratchet-baseline.json`):

**asUnknownAs (+4 since baseline commit, budget had 2 slack → +2 over):**
- `packages/app/src/web-ws-base-fix.ts:71,144,158` — 3 new `window as unknown as ...` casts (landed in #13438)
- `packages/ui/src/testing/e2e-runner/fixture-bundle.ts:145` — `tailwind() as unknown as AcceptedPlugin` (third-party type gap: tailwind PluginCreator vs PostCSS AcceptedPlugin under tsgo)

**nullishEmptyArray (+5 new, -4 removed elsewhere → +1 over):**
- `packages/core/src/runtime-env.ts:120` — `getBootConfigEnvAliases() ?? []` (#13356)
- plus new occurrences in `plugin-lifecycle.ts` / `action-tiering.ts` / `context-gates.ts`

## Root cause

The ratchet is only enforced locally via `bun run verify` — it is **not a CI gate**. So PRs land casts/empty-fallbacks without bumping (or reducing to) the baseline, drift accumulates silently, and the next person to run `verify` on pristine develop eats a red gate they didn't cause. Exactly the failure mode #13616 flagged; #13640 fixed step 1 but step 2 was already drifted.

## Fix (PR incoming)

Reduce the drift instead of bumping baselines: de-cast `web-ws-base-fix.ts`, guard the `envAliases` read in `runtime-env.ts`. The tailwind cast stays (genuinely load-bearing third-party type gap) — counters land at-or-below baseline without touching the baseline file.

**needs-human:** adding `audit:type-safety-ratchet` to a CI workflow requires a `.github/workflows` change, which agents don't touch by policy. Until it's a CI gate this will drift again.

Refs #13616, #13640, #13406.

— [sol-orch]

**Comment by lalalune** [comment]
Opened PR #13663 to fix the pristine-develop type-safety ratchet failure without bumping the baseline.

What changed:
- Removed the three `as unknown as` double-casts from `packages/app/src/web-ws-base-fix.ts` by declaring the injected WS globals on `Window`.
- Replaced the scoped `getBootConfigEnvAliases() ?? []` empty fallback in `packages/core/src/runtime-env.ts` with an explicit no-alias branch.

Verification:
- `bun run audit:type-safety-ratchet` now passes: `as unknown as` is 72/73 and scoped `?? []` is 581/581.
- `bunx @biomejs/biome check packages/app/src/web-ws-base-fix.ts packages/core/src/runtime-env.ts --no-errors-on-unmatched`
- `bun run --cwd packages/app test -- src/web-ws-base-fix.test.ts`
- `bun run --cwd packages/app typecheck`
- `bun run --cwd packages/core typecheck`
- `git diff --check`

**Comment by 0xSolace** [comment]
## Resolution + evidence

**Superseded mid-flight:** while my fix PR #13667 sat in the queue, Shaw landed the byte-for-byte-equivalent fix in **#13663** (merged as 0e2a0365927): same two de-cast sites (`web-ws-base-fix.ts` via typed `window` access, `runtime-env.ts` early-return instead of `?? []`), same disposition for the tailwind cast (stays, fits in budget). #13667 closed as superseded, branch deleted.

**Ratchet on pristine develop (035223a0638) is now GREEN:**
```
[type-safety-ratchet] as unknown as: 72 / 73
[type-safety-ratchet] `?? []` (core/agent/app-core): 581 / 581
```
exit 0, all other counters at-or-below baseline.

**Where `bun run verify` lands next** (ran the full chain on pristine develop):
1. `check:agents-claude` ✅ (fixture allowlist landed on develop)
2. `audit:type-safety-ratchet` ✅ (this issue — fixed)
3. `audit:error-policy-ratchet` ✅
4. turbo `typecheck lint` ❌ **NEW failure:** `@elizaos/cloud-api#typecheck` (tsgo):
```
packages/shared/src/config/brand-env-aliases.ts(143,34): error TS2551:
Property 'syncElizaKey' does not exist on type '{ readonly brandSuffix: "NAMESPACE"; readonly elizaKey: "ELIZA_NAMESPACE"; } | ... 39 more ...'
```
Introduced by #13632 (unified brand alias table, merged 22:55Z today). The `BRAND_ENV_ALIAS_DEFINITIONS` array is `as const` and only one entry carries `syncElizaKey`, so `definition.syncElizaKey` at line 143 fails on the union under cloud-api's tsgo config even though `@elizaos/shared`'s own typecheck passes. Reporting per lane scope, not fixing here — verify is still red on develop until that's addressed.

**Standing root cause remains:** the ratchet (and verify generally) is not a CI gate, so develop keeps accumulating breakage that only surfaces when someone runs `verify` locally. `.github/workflows` change = needs-human.

— [sol-orch]

**Comment by 0xSolace** [comment]
## Step 4 (turbo typecheck) — verified fixed, already in flight via #13664

**Root cause confirmed on pristine develop (d59db274402):** `@elizaos/shared` + `@elizaos/cloud-api` typecheck RED at `packages/shared/src/config/brand-env-aliases.ts:143` — `buildBrandEnvSyncAliases` reads `definition.syncElizaKey ?? definition.elizaKey`, but the `as const` array union only carries `syncElizaKey` on the 1/42 entry that declares it (the `PORT` sync entry from #13632). tsgo: `TS2551: Property 'syncElizaKey' does not exist`.

**No new PR needed — #13664 already fixes this and has auto-merge armed.** Shaw's #13664 replaces the `?? ` read with an `"syncElizaKey" in definition` narrowing (exactly approach (b) — no cast, no ratchet drift, no noise), plus a regression test for BRAND_UI_PORT precedence. Independently verified on pristine develop:

```
# with #13664 patch applied to pristine develop:
turbo run typecheck --filter=@elizaos/shared --filter=@elizaos/cloud-api --force
  Tasks:    63 successful, 63 total
# brand-env-aliases tests:
bun test packages/shared/src/utils/env.test.ts  →  13 pass, 0 fail
```

Auto-merge on #13664 was already enabled (by [sol-orch] an earlier lane); it's MERGEABLE, 0 failing checks, blocked only on 43 pending CI. Standing down on step 4 to avoid a duplicate-PR supersede race.

**Where `bun run verify` lands next (report-only, not fixing):** with steps 1-4 green, the remaining chain items surface pre-existing drift unrelated to #13658's typecheck fix:
- `audit:turbo-build-deps` — RED on pristine develop (phantom turbo.json overrides naming `build` for owner packages that don't define it: @elizaos/registry, example-browser-extension, example-farcaster, example-game-of-life; **plus a package.json cycle in qa-build**). Separate P1, own lane.
- `audit:scripts` — RED: `scripts/check-markdown-links.mjs` hardcodes 5 plugin tokens; needs allowlist or shared-seam discovery. Separate.
- `typecheck:dist` — depends on a full `turbo run build`, which currently fails at `eliza-react-example:build` (`MISSING_EXPORT "DEFAULT_CEREBRAS_TEXT_MODEL"` from core browser bundle via plugin-openai). Separate build-graph issue.

— [sol-orch]

**Comment by 0xSolace** [comment]
## [sol-verify] step-4 lane closeout — SUPERSEDED, confirmed green post-merge

Re-verified after #13664 (29c72ce114d) merged to develop:

- `packages/shared/src/config/brand-env-aliases.ts` now uses `"syncElizaKey" in definition` narrowing at the access site (lines 144-145) plus the optional `readonly syncElizaKey?: string` member — exactly the fix this lane was scoped to make. No casts, no `any`.
- Proof on pristine develop (51d008c851b): `bunx turbo run typecheck --filter=@elizaos/cloud-api` → **1 successful, 1 total** (exit 0). Previously RED at brand-env-aliases.ts:143.

No PR needed from this lane; worktree deleted. Standing down.
