### PR TITLE
ci(agent-image): harden boot gate (push verified image, post-health window)

### PR DESCRIPTION
**Pull request by 0xSolace**
## Follow-up to #8081

#8081 landed the boot-verification gate (build the image locally, run the real agent entrypoint against it, only push if it boots). It was merged before this hardening commit landed on the branch, so this PR carries the hardening on its own. It applies cleanly on top of current develop.

## What this hardens

- **Push the exact verified image.** The workflow now retags the locally-loaded `:ci-boot-verify` image (the one that just booted) and `docker push`es it, instead of running a second build-push. This removes the risk that a `cache-from` miss or a network-dependent Dockerfile step (fetching the latest `yt-dlp`) publishes a different image than the one that was verified. `provenance: false` keeps the loaded image single-platform so the retag-push ships identical content.
- **Post-health observation window.** A new `confirm_stable` keeps watching the container for a short window after health first comes up, so a crash that happens just after the server binds (async runtime/plugin init blowing up post-listen) still turns the gate RED instead of slipping through.
- **Tighter crash-signature list.** Narrowed to module-resolution and explicit fatal-startup markers (`Cannot find package/module`, `ERR_MODULE_NOT_FOUND`, `MODULE_NOT_FOUND`, `Failed to start`, `crashed during init`); dropped the over-broad `FATAL` and `Cannot read properties of undefined` so a benign log line cannot flap the gate. The container-exit and health-timeout checks remain the backstops.

## Proof

Re-verified locally via `--boot-verify-only` against fixture images:

GREEN on a bootable image:
```
[docker-ci-smoke] Health probe succeeded against the real entrypoint: .../api/health
{"ready":true,"runtime":"ok"}
[docker-ci-smoke] Boot verified: agent stayed up after health came up
GOOD_EXIT=0
```

RED on a broken image:
```
[docker-ci-smoke] Detected startup crash signature in container logs: 'Cannot find module'
[docker-ci-smoke] ERROR: Agent crashed on startup (matched 'Cannot find module'); image is NOT bootable
BROKEN_EXIT=1
```

Please review and do not merge yet.

<h3>Greptile Summary</h3>

This PR hardens the boot-verification gate introduced in #8081: instead of running a second `docker/build-push-action` after verification, it retags the locally-loaded `:ci-boot-verify` image and `docker push`es it directly, guaranteeing the published bytes are byte-for-byte what was tested. It also adds a 15-second post-health observation window (`confirm_stable`) so crashes that occur just after the server binds are still caught, and tightens the crash-pattern list to module-resolution and explicit fatal-startup markers.

- **Retag-and-push**: `provenance: false` keeps the loaded image single-platform; a shell loop tags and pushes each computed tag; digest is extracted from the first pushed tag for attestation.
- **`confirm_stable`**: nested function inside `boot_verify` that polls container liveness and scans logs for a configurable window (default 15 s) after health is first confirmed; `BOOT_STABLE_WINDOW_SEC` is not explicitly set in the workflow env.
- **Crash-pattern list**: `FATAL`, `UnhandledPromiseRejection`, and `Cannot read properties of undefined` removed; `MODULE_NOT_FOUND` added alongside the existing module-resolution patterns.

<h3>Confidence Score: 4/5</h3>

Safe to merge — the retag-and-push path correctly ships the verified image, and the post-health window adds a meaningful stability check.

The core retag-and-push logic correctly ships the verified image with no chance of a second build introducing drift. confirm_stable reads the full container log history rather than only post-health output, so a pre-health Failed-to-start entry that fell into the timing gap between the main loop's last log read and confirm_ok could flip the gate RED on a false positive. The primary digest extraction path (docker inspect LOCAL_IMAGE) is dead code since the ci-boot-verify tag was never pushed; the code always relies on the first_tag fallback. Both findings affect edge-case reliability and code clarity, not the correctness of the image that gets published.

Both changed files warrant a second look: docker-ci-smoke.sh for the full-history log scan in confirm_stable, and build-agent-image.yml for the digest-resolution fallback path.

<h3>Important Files Changed</h3>

| Filename | Overview |
|----------|----------|
| .github/workflows/build-agent-image.yml | Replaces second build-push with a shell retag+push loop over the verified local image; adds provenance: false to keep single-platform load; digest resolution always falls through to the first_tag fallback (primary LOCAL_IMAGE path is dead); attestation is conditionally guarded on non-empty digest. |
| packages/app-core/scripts/docker-ci-smoke.sh | Adds confirm_stable post-health observation window (default 15 s), narrows crash patterns to module-resolution and explicit fatal-startup markers, removes FATAL/UnhandledPromiseRejection/Cannot-read-properties; confirm_stable scans full log history which can false-positive on pre-health log entries that narrowly missed the main loop scan. |

</details>

<h3>Flowchart</h3>

```mermaid
%%{init: {'theme': 'neutral'}}%%
flowchart TD
    A[docker/build-push-action\nload=true, push=false\nprovenance=false\ntag: :ci-boot-verify] --> B[docker-ci-smoke.sh\n--boot-verify-only]
    B --> C{scan_crash in boot loop}
    C -- match found --> FAIL1[fail: crash signature]
    C -- no match --> D{container alive?}
    D -- no --> FAIL2[fail: container exited]
    D -- yes --> E{confirm_ok /api/health or /api/status}
    E -- timeout --> FAIL3[fail: timed out]
    E -- health served --> F[confirm_stable 15s window]
    F --> G{container alive AND no crash in logs?}
    G -- crash or exit --> FAIL4[fail: post-health crash]
    G -- stable --> H[Boot verified]
    H --> I[push step: retag and docker push each tag]
    I --> J[resolve digest via docker inspect first_tag]
    J --> K{digest non-empty?}
    K -- yes --> L[actions/attest-build-provenance]
    K -- no --> M[attestation skipped]
    L --> N[Make image public via GHCR API]
    M --> N
```

<details><summary><h3>Comments Outside Diff (1)</h3></summary>

1. `.github/workflows/build-agent-image.yml`, line 282-288 ([link](https://github.com/elizaos/eliza/blob/d43507a45b29f08ad4cfb060a2e0d3e682e024e7/.github/workflows/build-agent-image.yml#L282-L288)) 

   <a href="#">P2</a> **`BOOT_STABLE_WINDOW_SEC` is unset; `confirm_stable` exceeds `SMOKE_TIMEOUT_SEC`**

   `SMOKE_TIMEOUT_SEC: "180"` only governs the poll loop that waits for health to first appear; `confirm_stable` runs after health is confirmed and adds up to `BOOT_STABLE_WINDOW_SEC` seconds (default 15 s) beyond that. A run where health arrives close to the 180 s mark can therefore run for ~195 s before the smoke step exits. The job has a 60-minute cap so there is no practical breakage, but explicitly setting `BOOT_STABLE_WINDOW_SEC` alongside the other env vars would make the actual upper bound visible and override-able.

   Note: If this suggestion doesn't match your team's coding style, reply to this and let me know. I'll remember it for next time!

</details>

<sub>Reviews (1): Last reviewed commit: ["ci(agent-image): harden boot gate (push ..."](https://github.com/elizaos/eliza/commit/d43507a45b29f08ad4cfb060a2e0d3e682e024e7) | [Re-trigger Greptile](https://app.greptile.com/api/retrigger?id=34782075)</sub>

> Greptile also left **2 inline comments** on this PR.

### CODE REVIEW

**Comment by lalalune** [comment]
Fully superseded by develop's 'ci(agent-image): lowercase docker tag + harden boot gate (verified-image push, post-health window)' commit. Verified hunk-by-hunk: provenance:false on build-local, the docker tag/push loop reusing the verified :ci-boot-verify image, digest-via-RepoDigests + guarded attestation, the docker-ci-smoke.sh crash-pattern edits, and the confirm_stable post-health window are all already on develop. develop is a strict superset — its confirm_stable takes an RFC3339 checkpoint and scans only logs --since health, eliminating the false-positive risk this PR's full-log rescan has. No unique delta. Closing as superseded.
