### ISSUE TITLE
Fix current develop agent typecheck partial Response mock

### ISSUE THREAD

**Issue by lalalune** [elizaOS/eliza#19768]
## Problem

Current `develop` fails the required root `bun run verify` gate during `@elizaos/agent#typecheck`:

```text
packages/agent/src/api/cloud-pair-route.test.ts(453,34): error TS2352:
Conversion of type '{ ok: true; status: number; json: () => Promise<never>; }'
to type 'Response' may be a mistake...
```

The regression is in the stalled-response timeout test added by #19591. Its fetch mock returns a deliberately partial response object but casts it directly to the full DOM `Response` type.

## Acceptance criteria

- Model the fetch test double without an invalid direct structural cast.
- Keep the stalled-response timeout behavior covered.
- Pass the focused test and `packages/agent` typecheck.
- Restore the root verification path.

## Evidence

Reproduced on current `origin/develop` at `d69ddd617cd9c136481e0241411af5f124c7d9fe`.

AI provider/model: OpenAI / gpt-5.6-sol
Client / agent tooling: Codex desktop
Contribution skill revision: N/A - repository contribution skill is not available in this session
Attribution status: self-reported
— Codex

**Comment by lalalune** [comment]
CLAIMING: I will correct the invalid partial Response test double, retain the timeout-path coverage, run the focused agent tests and typecheck, and restore the root verification path.

AI provider/model: OpenAI / gpt-5.6-sol
Client / agent tooling: Codex desktop
Contribution skill revision: N/A - repository contribution skill is not available in this session
Attribution status: self-reported
— Codex

**Comment by lalalune** [comment]
Resolved independently on develop by commit 11ee8cb9108f0c14fe0f6f0db2fa46a0005a6abd, which removes the TS2352 root-gate failure. I re-ran the complete root verification after the Cloud persona fix merged: 350/350 workspace tasks and every repository audit passed.

PR #19778 is therefore being closed as superseded rather than merging overlapping test-only churn. Its stronger real-Response alternative remains available in the PR history if maintainers prefer that modeling later.

AI provider/model: OpenAI / gpt-5.6-sol
Client / agent tooling: Codex desktop
Contribution skill revision: N/A - repository contribution skill is not available in this session
Attribution status: self-reported
— Codex

**Comment by lalalune** [comment]
Current develop now contains `11ee8cb9108f0c14fe0f6f0db2fa46a0005a6abd`, which makes the partial response boundary explicit and restores the agent/root typecheck. A stronger real-Response variant was validated locally (focused 21/21, agent typecheck, forced root verify 350/350) but is no longer required to unblock the release and will not be pushed as a duplicate. Closing as resolved by current develop.

**Comment by lalalune** [comment]
Closing as completed on current `develop` by `11ee8cb9108f0c14fe0f6f0db2fa46a0005a6abd` (`test(agent): make partial response double explicit`).

The current test now uses an explicit double assertion for the deliberately partial stalled-response object rather than the invalid direct structural cast, while retaining the abort-driven 15-second timeout regression. The implementing agent reports exact-current root verification at 350/350 with all audits passing after the unrelated persona repair landed; superseded PR #19778 was correctly closed instead of duplicating the upstream fix.

AI provider/model: OpenAI / gpt-5.6-sol
Client / agent tooling: Codex Desktop
Contribution skill revision: N/A - no contribution skill used
Attribution status: self-reported
— [codex]
