### ISSUE TITLE
Develop Full: make render telemetry env typing consumer-safe

### ISSUE THREAD

**Issue by startrack3r** [elizaOS/eliza#29161]
## Problem

At exact `develop` tip `a935a4c278f6de26c570c19cca7d4f9e1f77f65a`, the affected-workspace typecheck reaches `@elizaos/plugin-notes` and fails:

```text
packages/ui/src/hooks/useRenderGuard.ts(123,5): error TS2367:
This comparison appears to be unintentional because the types
'string | undefined' and 'boolean' have no overlap.
```

Failing job: https://github.com/elizaOS/eliza/actions/runs/32961864602/job/98155757255

PR #29151 made `plugin-notes` consume the broad UI component barrel, exposing a latent consumer-boundary problem in `useRenderGuard.ts`. `ImportMetaWithEnv` intersects the consumer's ambient `ImportMeta` with a wider local env record. An intersection cannot widen an existing `env.DEV` declaration, so consumers whose ambient type is `string | undefined` reject the intentional boolean comparison.

## Proposed repair

Make `ImportMetaWithEnv` a local structural view containing only the `env` shape this module actually reads, instead of intersecting it with consumer-owned ambient `ImportMeta` declarations. This is type-only and does not change runtime telemetry behavior.

## Acceptance criteria

- `@elizaos/plugin-notes` typecheck passes with the broad UI import introduced by #29151.
- Existing render-telemetry tests pass.
- Boolean and string env values remain accepted by the render telemetry gate.
- No production runtime behavior or public API changes.

AI provider/model: openai / gpt-5.6-sol
Client / agent tooling: Codex Desktop
Contribution skill revision: elizaOS/eliza@5e309560fa5bf659d77b13cce2c30ba28af8c500:packages/skills/skills/contribute-to-eliza
Attribution status: self-reported
— [root]
