### ISSUE TITLE
develop: merge bfcda9400f carried an unreviewed recovery snapshot that reverts MESSAGE manage_server and other develop work, and breaks install/verify

### ISSUE THREAD

**Issue by Prabhat1308** [elizaOS/eliza#32578]
**Describe the bug**

Merge `bfcda9400f` ("Integrate progressive content with current storage, assistant and provider owners", 2026-09-23) merged branch `251fba377d`. That branch's first commit, `3b5a6183f7`, describes itself as:

> Recover the surviving index after loss of the temporary worktree. This snapshot is not reviewed or validated for merge.

The snapshot comes from a worktree older than the branch's own merge base (`9bd31de1ac`). When it was ported into the current owner packages, it replaced develop's newer file contents instead of applying only its intended edits. As a result, develop lost shipped behavior and does not build.

Behavior lost on develop at `47509b2fcf`:

- **MESSAGE `manage_server` op is gone.** `plugins/plugin-assistant/src/features/advanced-capabilities/actions/message.ts` had 64 `manage_server` references before the merge and has 0 after it. The op, its authorization (`authorizeManageServerDestination`), its types, and its description and compressed-surface text are all removed. `manage_server` was already present at the branch's merge base, so the snapshot did not intend to remove it.
- **An item cap is back on model-facing reads.** The same file replaces `requestedLimit` (a floor with no cap) with `clampLimit(value, fallback, max)` at `message.ts:199`, `:4150`, and `:4363`. This contradicts the root `CLAUDE.md` prompt-integrity contract.
- **Duplicated and misplaced file headers.** `message.ts` now contains its `/** MESSAGE — … */` header twice, placed after imports. Similar header moves appear in `documents/service.ts`, `plugin-inmemorydb/runtime.ts`, and `readAttachmentAction.ts`.
- **Develop-only code dropped in other files.** Lines that exist on the pre-merge develop parent (`bfcda9400f^1`) but not at the merge base are missing from the merge result, so the branch could never have intentionally changed them:

| develop-only lines dropped | file |
| --- | --- |
| 227 of 5607 | `plugins/plugin-assistant/src/features/advanced-capabilities/actions/message.ts` |
| 49 of 2694 | `plugins/plugin-inmemorydb/runtime.ts` |
| 42 of 3281 | `plugins/plugin-assistant/src/features/documents/service.ts` |
| 22 of 1598 | `plugins/plugin-assistant/src/services/message/processor.ts` |
| 21 of 623 | `plugins/plugin-assistant/src/features/documents/__tests__/search.test.ts` |
| 15 of 1030 | `plugins/plugin-assistant/src/features/working-memory/readAttachmentAction.ts` |
| 11 of 262 | `plugins/plugin-assistant/src/features/documents/__tests__/actions-progressive-read.test.ts` |
| 9 of 323 | `plugins/plugin-sql/src/base.ts` |
| 8 of 1724 | `plugins/plugin-assistant/src/features/documents/actions.ts` |
| 3 of 65 | `plugins/plugin-cli-inference/index.ts` |
| 1 of 77 | `plugins/plugin-sql/src/__tests__/integration/document-list-query.real.test.ts` |
| 1 of 54 | `plugins/plugin-coding-tools/src/actions/bash.test.ts` |
| 1 of 2440 | `plugins/plugin-assistant/src/services/message/pipeline.ts` |
| 1 of 197 | `plugins/plugin-assistant/src/features/documents/service-batch-embed.test.ts` |
| 1 of 3 | `packages/scenario-runner/test/scenarios/deterministic-progressive-content-actions.scenario.ts` |
| 1 of 13 | `packages/app-core/scripts/serve-real-local-agent.ts` |

The table is produced by a line-set heuristic, so a few entries may be deliberate rewrites; `message.ts`, `documents/service.ts`, `services/message/processor.ts`, and `plugin-inmemorydb/runtime.ts` need a real re-port. Base content that the snapshot deleted, such as `manage_server`, does not appear in the table at all, so the true blast radius is larger.

**Build breakage from the same merge.** A fresh `bun install` fails in the `@elizaos/core` build: `Could not resolve "uuid"`. `bun run verify` also fails:

```text
[audit-tsconfig-workspace-resolution] @elizaos/plugin-inbox typecheck: unresolved @elizaos/core/node imported by plugins/plugin-google-workspace/src/gmail-content-cache.ts
@elizaos/plugin-assistant:build: src/features/trajectories/TrajectoriesService.ts(69,3): error TS2300: Duplicate identifier 'roomId'.
plugins/plugin-assistant/src/features/advanced-capabilities/actions/message.ts(3910,5): error TS2304: Cannot find name 'requestedLimit'.
plugins/plugin-assistant/src/features/advanced-capabilities/actions/message.ts(3956,60): error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
plugins/plugin-inmemorydb/runtime.ts(1833,71): error TS18048: 'limit' is possibly 'undefined'.
```

The first three are mechanical and are fixed in the linked PR. The `message.ts` and `inmemorydb` errors are symptoms of the stale content above. Making them compile in isolation would cement the regression, so that PR deliberately leaves them alone.

**To Reproduce**

```bash
git checkout 47509b2fcf
bun install          # fails: packages/core build, Could not resolve "uuid"
git show 3b5a6183f7 --format=%B -s
git show bfcda9400f^1:plugins/plugin-assistant/src/features/advanced-capabilities/actions/message.ts | grep -c manage_server   # 64
git show bfcda9400f:plugins/plugin-assistant/src/features/advanced-capabilities/actions/message.ts | grep -c manage_server     # 0
```

**Expected behavior**

Develop keeps every capability that existed before the merge, including `MESSAGE manage_server` and uncapped read limits. The progressive-content work is re-applied as edits on top of the current owner files. Fresh install and `bun run verify` pass.

Suggested repair: for each affected file, take `bfcda9400f^1` and re-apply only the progressive-content edits from the branch commits after the snapshot (`5eee9013b3`..`251fba377d`), plus the snapshot hunks the author confirms were intended. A plain three-way merge of `bfcda9400f`, `9bd31de1ac`, and `bfcda9400f^1` for `message.ts` produces 39 conflicts, so the author of the snapshot needs to decide which hunks were intended.

**Screenshots / recording of the wrong behavior (required for anything visible)**

N/A - build and runtime-surface regression; the reproduction commands above show it.

**Evidence / reproduction proof**

- [x] MP4 recording or JPG screenshots of the broken behavior: N/A - no rendered surface changed.
- [x] Backend logs and frontend console/network logs: the build and audit output above, from a local checkout at `47509b2fcf` (Bun 1.3.14, macOS arm64).
- [x] Real-LLM trajectory: N/A - I have not driven the missing `manage_server` op through a live model; its removal is visible in source.
- [x] Domain artifacts: the per-file table above, computed from `bfcda9400f^1`, `bfcda9400f`, and `9bd31de1ac`.

AI provider/model: anthropic / claude-opus-5-5
Client / agent tooling: claude-code
Contribution skill revision: N/A - ordinary GitHub contribution without optional run evidence
Attribution status: self-reported
— [contributor]
